const formData = {
    invoice_type_id: '',
    type: '',
    invoice_no: 'INV-TEST-001',
    invoice_date: '',
    gra_no: '',
    date: '',
    dis_no: '',
    dis_date: '',
    pay_name: '',
    delivery: '',
    invoice_address: '',
    delivery_address: '',
    state: '',
    state_code: '',
    dly_state_code: '',
    po_no: '',
    po_date: '',
    agent_name: '',
    due_days: '',
    due_date: '',
    payment: '',
    pmt_ref_no: '',
    transport: '',
    truck_no: '',
    transport_mode: '',
    freight_mode: '',
    lr_no: '',
    lr_date: '',
    lr_team: '',
    gst_no: '',
    other_char_1: '',
    other_char_value_1: '',
    total_qty: 0,
    gross_amount: 0,
    gross_weight: '',
    discount_pct: 0,
    discount_amount: 0,
    taxable_amount: 0,
    sgst: 0,
    cgst: 0,
    igst: 0,
    other_charges: 0,
    round_off: 0,
    net_amount: 0,
    status: 'Draft'
};
const items = [{ design_no: '', hsn_code: '', description: '', total_bale: '', uom: 'MTR', qty: '', rate: '', amount: 0 }];
const extra = {};
const payload = {
      invoice_no: formData.invoice_no,
      invoice_date: formData.invoice_date,
      party_name: formData.pay_name || null,
      billing_address: formData.invoice_address || null,
      delivery_address: formData.delivery_address || null,
      state: formData.state || null,
      state_code: formData.state_code || null,
      gst_no: formData.gst_no || null,
      hsn_code: items[0]?.hsn_code || null,
      total_qty: Number(formData.total_qty) || 0,
      gross_weight: Number(formData.gross_weight) || 0,
      gross_amount: Number(formData.gross_amount) || 0,
      discount_pct: Number(formData.discount_pct) || 0,
      discount_amount: Number(formData.discount_amount) || 0,
      taxable_amount: Number(formData.taxable_amount) || 0,
      sgst: Number(formData.sgst) || 0,
      cgst: Number(formData.cgst) || 0,
      igst: Number(formData.igst) || 0,
      other_charges: Number(formData.other_charges) || 0,
      round_off: Number(formData.round_off) || 0,
      net_amount: Number(formData.net_amount) || 0,
      remarks: JSON.stringify(extra),
      status: formData.status || 'Draft',
      
      items: items.map(item => ({
        design_no: item.design_no || null,
        description: item.description || null,
        total_bale: item.total_bale ? Number(item.total_bale) : null,
        uom: item.uom || 'MTR',
        qty: Number(item.qty) || 0,
        rate: Number(item.rate) || 0,
        amount: Number(item.amount) || 0
      }))
    };
console.log(JSON.stringify(payload));
