"""Add User Management fields

Revision ID: 053cae0add22
Revises: c06f49524b09
Create Date: 2026-05-26 15:26:29.977691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053cae0add22'
down_revision: Union[str, None] = 'c06f49524b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_general_master_category', table_name='general_master')
    op.drop_index('ix_general_master_id', table_name='general_master')
    op.drop_table('general_master')
    op.add_column('employees', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('employees', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('modified_by', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('access_expiry_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'access_expiry_date')
    op.drop_column('employees', 'modified_by')
    op.drop_column('employees', 'created_by')
    op.drop_column('employees', 'last_login')
    op.create_table('general_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='general_master_pkey')
    )
    op.create_index('ix_general_master_id', 'general_master', ['id'], unique=False)
    op.create_index('ix_general_master_category', 'general_master', ['category'], unique=False)
    # ### end Alembic commands ###
