"""Add warp delivery fields

Revision ID: 0cfc0af9f126
Revises: e0c14510b1a3
Create Date: 2026-05-26 20:14:25.305397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cfc0af9f126'
down_revision: Union[str, None] = 'e0c14510b1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warp_deliveries', sa.Column('ref_no', sa.String(length=50), nullable=True))
    op.add_column('warp_deliveries', sa.Column('sizing_name', sa.String(length=255), nullable=True))
    op.add_column('warp_deliveries', sa.Column('entry_type', sa.String(length=50), nullable=True))
    op.add_column('warp_deliveries', sa.Column('bpo_no', sa.String(length=50), nullable=True))
    op.add_column('warp_deliveries', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('warp_deliveries', sa.Column('set_id', sa.String(length=50), nullable=True))
    op.add_column('warp_deliveries', sa.Column('warp_ends', sa.Integer(), nullable=True))
    op.add_column('warp_deliveries', sa.Column('yarn_count', sa.String(length=50), nullable=True))
    op.add_column('warp_deliveries', sa.Column('vendor_po_no', sa.String(length=50), nullable=True))
    op.add_column('warp_deliveries', sa.Column('po_date', sa.Date(), nullable=True))
    op.add_column('warp_deliveries', sa.Column('order_mtrs', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('warp_deliveries', sa.Column('with_crimp', sa.String(length=50), nullable=True))
    op.add_column('warp_deliveries', sa.Column('delivered_mtrs', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('warp_deliveries', sa.Column('total_beams', sa.Integer(), nullable=True))
    op.add_column('warp_deliveries', sa.Column('total_exptd_mtrs', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warp_deliveries', 'total_exptd_mtrs')
    op.drop_column('warp_deliveries', 'total_beams')
    op.drop_column('warp_deliveries', 'delivered_mtrs')
    op.drop_column('warp_deliveries', 'with_crimp')
    op.drop_column('warp_deliveries', 'order_mtrs')
    op.drop_column('warp_deliveries', 'po_date')
    op.drop_column('warp_deliveries', 'vendor_po_no')
    op.drop_column('warp_deliveries', 'yarn_count')
    op.drop_column('warp_deliveries', 'warp_ends')
    op.drop_column('warp_deliveries', 'set_id')
    op.drop_column('warp_deliveries', 'address')
    op.drop_column('warp_deliveries', 'bpo_no')
    op.drop_column('warp_deliveries', 'entry_type')
    op.drop_column('warp_deliveries', 'sizing_name')
    op.drop_column('warp_deliveries', 'ref_no')
    # ### end Alembic commands ###
