"""Add dyed yarn received

Revision ID: 10c1a8bac83a
Revises: c777b2fd0966
Create Date: 2026-05-26 17:49:44.497789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c1a8bac83a'
down_revision: Union[str, None] = 'c777b2fd0966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
