"""Add DesignEntry model

Revision ID: 1f6668e700c8
Revises: 261ad5b3839d
Create Date: 2026-05-26 16:31:16.454547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6668e700c8'
down_revision: Union[str, None] = '261ad5b3839d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_general_master_category', table_name='general_master')
    op.drop_index('ix_general_master_id', table_name='general_master')
    op.drop_table('general_master')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='general_master_pkey')
    )
    op.create_index('ix_general_master_id', 'general_master', ['id'], unique=False)
    op.create_index('ix_general_master_category', 'general_master', ['category'], unique=False)
    # ### end Alembic commands ###
