"""add_dyed_yarn_delivery_fields_layout

Revision ID: 1fb5ec81541e
Revises: 32a0d67ecf1d
Create Date: 2026-07-02 11:57:36.790499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fb5ec81541e'
down_revision: Union[str, None] = '32a0d67ecf1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_JobWork_Delivery_Detail_DetailID', table_name='JobWork_Delivery_Detail')
    op.drop_table('JobWork_Delivery_Detail')
    op.drop_index('ix_loom_master_id', table_name='loom_master')
    op.drop_index('ix_loom_master_loom_name', table_name='loom_master')
    op.drop_table('loom_master')
    op.drop_index('ix_operator_master_id', table_name='operator_master')
    op.drop_index('ix_operator_master_operator_id', table_name='operator_master')
    op.drop_table('operator_master')
    op.drop_index('ix_production_logs_id', table_name='production_logs')
    op.drop_table('production_logs')
    op.drop_index('ix_JobWork_Delivery_Header_DCNo', table_name='JobWork_Delivery_Header')
    op.drop_index('ix_JobWork_Delivery_Header_DeliveryID', table_name='JobWork_Delivery_Header')
    op.drop_index('ix_JobWork_Delivery_Header_DeliveryNo', table_name='JobWork_Delivery_Header')
    op.drop_table('JobWork_Delivery_Header')
    op.drop_index('ix_loom_allocations_id', table_name='loom_allocations')
    op.drop_table('loom_allocations')
    op.drop_index('ix_Stock_Ledger_Entry_id', table_name='Stock_Ledger_Entry')
    op.drop_table('Stock_Ledger_Entry')
    op.drop_index('ix_yarn_purchase_items_id', table_name='yarn_purchase_items')
    op.drop_table('yarn_purchase_items')
    op.alter_column('buyer_order_expenses', 'currency',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('buyer_order_items', 'currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('buyer_orders', 'credit_days')
    op.drop_column('cloth_purchase_pos', 'tax_type')
    op.alter_column('design_entry', 'yarn_details',
               existing_type=sa.TEXT(),
               type_=sa.String(length=4000),
               existing_nullable=True)
    op.alter_column('design_entry', 'fabric_design_details',
               existing_type=sa.TEXT(),
               type_=sa.String(length=4000),
               existing_nullable=True)
    op.drop_column('design_entry', 'pick_less')
    op.drop_column('design_entry', 'reed_less')
    op.drop_column('design_entry', 'onloom_pick')
    op.drop_column('design_entry', 'onloom_reed')
    op.drop_column('design_entry', 'grey_reed')
    op.drop_column('design_entry', 'fabric_width_grey')
    op.drop_column('design_entry', 'gsm')
    op.drop_column('design_entry', 'reed_space')
    op.drop_column('design_entry', 'glm')
    op.drop_column('design_entry', 'fab_width_reed_add')
    op.drop_column('design_entry', 'grey_reed_add')
    op.alter_column('despatch_planning', 'design_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('despatch_planning', 'uom',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('despatch_planning', 'currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('dyed_yarn_deliveries', 'dc_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('dyed_yarn_deliveries', 'transport',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('dyed_yarn_deliveries', 'delivery_time',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('dyed_yarn_deliveries', 'certificate_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('ix_dyed_yarn_deliveries_dc_no', table_name='dyed_yarn_deliveries')
    op.create_index(op.f('ix_dyed_yarn_deliveries_dc_no'), 'dyed_yarn_deliveries', ['dc_no'], unique=False)
    op.create_index(op.f('ix_dyed_yarn_deliveries_delivery_no'), 'dyed_yarn_deliveries', ['delivery_no'], unique=True)
    op.drop_column('dyed_yarn_deliveries', 'branch')
    op.drop_column('dyed_yarn_deliveries', 'tax_value')
    op.drop_column('dyed_yarn_deliveries', 'total_rin_kgs')
    op.drop_column('dyed_yarn_deliveries', 'tcs')
    op.drop_column('dyed_yarn_deliveries', 'insurance')
    op.drop_column('dyed_yarn_deliveries', 'processor_address')
    op.drop_column('dyed_yarn_deliveries', 'dyeing_batch_no')
    op.drop_column('dyed_yarn_deliveries', 'sgst')
    op.drop_column('dyed_yarn_deliveries', 'total_delv_kgs')
    op.drop_column('dyed_yarn_deliveries', 'financial_year')
    op.drop_column('dyed_yarn_deliveries', 'buyer_order')
    op.drop_column('dyed_yarn_deliveries', 'dyeing_po_date')
    op.drop_column('dyed_yarn_deliveries', 'company')
    op.drop_column('dyed_yarn_deliveries', 'customer_po_no')
    op.drop_column('dyed_yarn_deliveries', 'mobile_no')
    op.drop_column('dyed_yarn_deliveries', 'tds')
    op.drop_column('dyed_yarn_deliveries', 'advance_received')
    op.drop_column('dyed_yarn_deliveries', 'received_by')
    op.drop_column('dyed_yarn_deliveries', 'dc_no_alt')
    op.drop_column('dyed_yarn_deliveries', 'mobile_number')
    op.drop_column('dyed_yarn_deliveries', 'balance_amount')
    op.drop_column('dyed_yarn_deliveries', 'contact_person')
    op.drop_column('dyed_yarn_deliveries', 'status')
    op.drop_column('dyed_yarn_deliveries', 'design_type')
    op.drop_column('dyed_yarn_deliveries', 'expected_return_date')
    op.drop_column('dyed_yarn_deliveries', 'dispatch_from')
    op.drop_column('dyed_yarn_deliveries', 'net_amount')
    op.drop_column('dyed_yarn_deliveries', 'cost')
    op.drop_column('dyed_yarn_deliveries', 'lr_date')
    op.drop_column('dyed_yarn_deliveries', 'add_date')
    op.drop_column('dyed_yarn_deliveries', 'igst')
    op.drop_column('dyed_yarn_deliveries', 'delivery_challan_type')
    op.drop_column('dyed_yarn_deliveries', 'buyer')
    op.alter_column('dyed_yarn_delivery_items', 'count',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('dyed_yarn_delivery_items', 'color',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('dyed_yarn_delivery_items', 'stock',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.drop_column('dyed_yarn_delivery_items', 'stock_qty')
    op.drop_column('dyed_yarn_delivery_items', 'purchase_order_no')
    op.create_index(op.f('ix_dyed_yarn_received_receipt_no'), 'dyed_yarn_received', ['receipt_no'], unique=True)
    op.drop_column('dyed_yarn_received_items', 'received_count')
    op.drop_column('dyed_yarn_received_items', 'delivery_count')
    op.alter_column('eway_bill_items', 'bill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_eway_bill_items_id'), 'eway_bill_items', ['id'], unique=False)
    op.drop_constraint('eway_bill_items_bill_id_fkey', 'eway_bill_items', type_='foreignkey')
    op.create_foreign_key(None, 'eway_bill_items', 'eway_bills', ['bill_id'], ['id'])
    op.drop_constraint('eway_bills_eway_bill_no_key', 'eway_bills', type_='unique')
    op.create_index(op.f('ix_eway_bills_eway_bill_no'), 'eway_bills', ['eway_bill_no'], unique=True)
    op.create_index(op.f('ix_eway_bills_id'), 'eway_bills', ['id'], unique=False)
    op.drop_column('fabric_dyeing_pos', 'tax_type')
    op.drop_column('general_master', 'is_active')
    op.drop_column('general_master', 'code')
    op.drop_column('general_master', 'description')
    op.alter_column('grey_yarn_deliveries', 'delivery_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'delivery_mode',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'design_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'order_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'transport',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'certificate_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint('grey_yarn_deliveries_party_id_fkey', 'grey_yarn_deliveries', type_='foreignkey')
    op.drop_column('grey_yarn_deliveries', 'net_amount')
    op.drop_column('grey_yarn_deliveries', 'gross_amount')
    op.drop_column('grey_yarn_deliveries', 'remarks')
    op.drop_column('grey_yarn_deliveries', 'igst')
    op.drop_column('grey_yarn_deliveries', 'total_kgs')
    op.drop_column('grey_yarn_deliveries', 'party_id')
    op.drop_column('grey_yarn_deliveries', 'sgst')
    op.alter_column('grey_yarn_delivery_items', 'count',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'color',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'stock',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'total_kgs',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('grey_yarn_delivery_items', 'yarn_type')
    op.drop_column('grey_yarn_delivery_items', 'lot_no')
    op.alter_column('packing_slips', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('party_master', 'pin_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('party_master', 'currency',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('party_master', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('party_master', 'gst_no',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('party_master', 'pan_no',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('party_master', 'tin_no',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('party_master', 'cst_no',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('party_master', 'credit_limit',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('processing_po_items', 'fabric_name')
    op.drop_column('processing_po_items', 'width')
    op.drop_column('processing_po_items', 'fabric_type')
    op.drop_column('processing_po_items', 'uom')
    op.drop_column('processing_po_items', 'qty')
    op.drop_column('processing_po_items', 'lot_no')
    op.drop_column('processing_po_items', 'gsm')
    op.drop_column('processing_po_items', 'color')
    op.drop_column('processing_po_items', 'batch_no')
    op.drop_column('processing_po_items', 'fabric_code')
    op.drop_column('processing_pos', 'loading_charge')
    op.drop_column('processing_pos', 'delivery_instructions')
    op.drop_column('processing_pos', 'sgst_pct')
    op.drop_column('processing_pos', 'buyer_name')
    op.drop_column('processing_pos', 'processing_charge')
    op.drop_column('processing_pos', 'buyer_order_no')
    op.drop_column('processing_pos', 'cgst_amount')
    op.drop_column('processing_pos', 'taxable_value')
    op.drop_column('processing_pos', 'igst_pct')
    op.drop_column('processing_pos', 'transport_name')
    op.drop_column('processing_pos', 'cgst_pct')
    op.drop_column('processing_pos', 'supplier_processing_unit')
    op.drop_column('processing_pos', 'department')
    op.drop_column('processing_pos', 'igst_amount')
    op.drop_column('processing_pos', 'payment_terms')
    op.drop_column('processing_pos', 'supplier_code')
    op.drop_column('processing_pos', 'packing_charge')
    op.drop_column('processing_pos', 'other_charges')
    op.drop_column('processing_pos', 'terms_conditions')
    op.drop_column('processing_pos', 'indent_no')
    op.drop_column('processing_pos', 'dispatch_mode')
    op.drop_column('processing_pos', 'vehicle_no')
    op.drop_column('processing_pos', 'transport_charge')
    op.drop_column('processing_pos', 'sales_order_no')
    op.drop_column('processing_pos', 'unloading_charge')
    op.drop_column('processing_pos', 'sgst_amount')
    op.drop_column('processing_pos', 'production_order_no')
    op.drop_column('processing_pos', 'delivery_location')
    op.alter_column('sales_invoices', 'state_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('sales_invoices', 'currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('twisting_doubling_po_items', 'yarn_name')
    op.drop_column('twisting_doubling_po_items', 'lot_no')
    op.drop_column('twisting_doubling_po_items', 'qty_kg')
    op.drop_column('twisting_doubling_po_items', 'shade')
    op.drop_column('twisting_doubling_po_items', 'yarn_code')
    op.drop_column('twisting_doubling_po_items', 'rate_per_kg')
    op.drop_column('twisting_doubling_pos', 'department')
    op.drop_column('twisting_doubling_pos', 'indent_no')
    op.drop_column('twisting_doubling_pos', 'sales_order_no')
    op.drop_column('twisting_doubling_pos', 'round_off')
    op.drop_column('twisting_doubling_pos', 'production_order_no')
    op.drop_column('twisting_doubling_pos', 'taxable_value')
    op.drop_column('warp_design_items', 'beam_type')
    op.drop_column('warping_sizing_pos', 'tax_type')
    op.drop_column('weaving_pos', 'tax_type')
    op.drop_column('yarn_dyeing_po_items', 'yarn_type')
    op.drop_column('yarn_dyeing_po_items', 'shade_name')
    op.drop_column('yarn_dyeing_po_items', 'yarn_name')
    op.drop_column('yarn_dyeing_po_items', 'mill_name')
    op.drop_column('yarn_dyeing_po_items', 'qty_kg')
    op.drop_column('yarn_dyeing_po_items', 'yarn_code')
    op.drop_column('yarn_dyeing_po_items', 'rate_per_kg')
    op.drop_column('yarn_dyeing_po_items', 'shade_code')
    op.drop_column('yarn_dyeing_pos', 'department')
    op.drop_column('yarn_dyeing_pos', 'buyer_order_no')
    op.drop_column('yarn_dyeing_pos', 'sales_order_no')
    op.drop_column('yarn_dyeing_pos', 'production_order_no')
    op.drop_column('yarn_dyeing_pos', 'indent_no')
    op.alter_column('yarn_inward_items', 'lot_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('yarn_inward_items', 'rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('yarn_inward_items', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('yarn_inward_items', 'yarn_type')
    op.drop_column('yarn_inward_items', 'count')
    op.drop_column('yarn_inward_items', 'cones')
    op.drop_column('yarn_inward_items', 'stock')
    op.drop_column('yarn_inward_items', 'total_kgs')
    op.drop_column('yarn_inward_items', 'color')
    op.alter_column('yarn_inwards', 'gross_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('yarn_inwards', 'net_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint('yarn_inwards_party_id_fkey', 'yarn_inwards', type_='foreignkey')
    op.drop_column('yarn_inwards', 'dc_no')
    op.drop_column('yarn_inwards', 'party_name')
    op.drop_column('yarn_inwards', 'insurance')
    op.drop_column('yarn_inwards', 'design_no')
    op.drop_column('yarn_inwards', 'inv_no')
    op.drop_column('yarn_inwards', 'igst')
    op.drop_column('yarn_inwards', 'dc_date')
    op.drop_column('yarn_inwards', 'total_kgs')
    op.drop_column('yarn_inwards', 'party_id')
    op.drop_column('yarn_inwards', 'receive_mode')
    op.drop_column('yarn_inwards', 'order_no')
    op.drop_column('yarn_inwards', 'inv_date')
    op.drop_column('yarn_inwards', 'sgst')
    op.alter_column('yarn_purchase_orders', 'design_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('yarn_purchase_orders', 'net_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint('yarn_purchase_orders_party_id_fkey', 'yarn_purchase_orders', type_='foreignkey')
    op.drop_column('yarn_purchase_orders', 'order_type')
    op.drop_column('yarn_purchase_orders', 'total_amount')
    op.drop_column('yarn_purchase_orders', 'party_name')
    op.drop_column('yarn_purchase_orders', 'igst')
    op.drop_column('yarn_purchase_orders', 'payment_terms')
    op.drop_column('yarn_purchase_orders', 'party_id')
    op.drop_column('yarn_purchase_orders', 'delivery_date')
    op.drop_column('yarn_purchase_orders', 'cgst')
    op.drop_column('yarn_purchase_orders', 'sgst')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yarn_purchase_orders', sa.Column('sgst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('cgst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('delivery_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('payment_terms', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('igst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('party_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('total_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('order_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key('yarn_purchase_orders_party_id_fkey', 'yarn_purchase_orders', 'party_master', ['party_id'], ['id'])
    op.alter_column('yarn_purchase_orders', 'net_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('yarn_purchase_orders', 'design_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.add_column('yarn_inwards', sa.Column('sgst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('inv_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('order_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('receive_mode', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('total_kgs', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('dc_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('igst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('inv_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('design_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('insurance', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('party_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('dc_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key('yarn_inwards_party_id_fkey', 'yarn_inwards', 'party_master', ['party_id'], ['id'])
    op.alter_column('yarn_inwards', 'net_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('yarn_inwards', 'gross_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=True)
    op.add_column('yarn_inward_items', sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('yarn_inward_items', sa.Column('total_kgs', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_inward_items', sa.Column('stock', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('yarn_inward_items', sa.Column('cones', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('yarn_inward_items', sa.Column('count', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('yarn_inward_items', sa.Column('yarn_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('yarn_inward_items', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('yarn_inward_items', 'rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('yarn_inward_items', 'lot_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.add_column('yarn_dyeing_pos', sa.Column('indent_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('yarn_dyeing_pos', sa.Column('production_order_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('yarn_dyeing_pos', sa.Column('sales_order_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('yarn_dyeing_pos', sa.Column('buyer_order_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('yarn_dyeing_pos', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('yarn_dyeing_po_items', sa.Column('shade_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('yarn_dyeing_po_items', sa.Column('rate_per_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_dyeing_po_items', sa.Column('yarn_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('yarn_dyeing_po_items', sa.Column('qty_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_dyeing_po_items', sa.Column('mill_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yarn_dyeing_po_items', sa.Column('yarn_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yarn_dyeing_po_items', sa.Column('shade_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('yarn_dyeing_po_items', sa.Column('yarn_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('tax_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('warping_sizing_pos', sa.Column('tax_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('warp_design_items', sa.Column('beam_type', sa.VARCHAR(length=50), server_default=sa.text("'Warp Beam1'::character varying"), autoincrement=False, nullable=True))
    op.add_column('twisting_doubling_pos', sa.Column('taxable_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('twisting_doubling_pos', sa.Column('production_order_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('twisting_doubling_pos', sa.Column('round_off', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('twisting_doubling_pos', sa.Column('sales_order_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('twisting_doubling_pos', sa.Column('indent_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('twisting_doubling_pos', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('twisting_doubling_po_items', sa.Column('rate_per_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('twisting_doubling_po_items', sa.Column('yarn_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('twisting_doubling_po_items', sa.Column('shade', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('twisting_doubling_po_items', sa.Column('qty_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('twisting_doubling_po_items', sa.Column('lot_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('twisting_doubling_po_items', sa.Column('yarn_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('sales_invoices', 'currency',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('sales_invoices', 'state_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.add_column('processing_pos', sa.Column('delivery_location', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('production_order_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('sgst_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('unloading_charge', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('sales_order_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('transport_charge', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('vehicle_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('dispatch_mode', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('indent_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('terms_conditions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('other_charges', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('packing_charge', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('supplier_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('payment_terms', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('igst_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('supplier_processing_unit', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('cgst_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('transport_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('igst_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('taxable_value', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('cgst_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('buyer_order_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('processing_charge', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('buyer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('sgst_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('delivery_instructions', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('processing_pos', sa.Column('loading_charge', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('processing_po_items', sa.Column('fabric_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('processing_po_items', sa.Column('batch_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('processing_po_items', sa.Column('color', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('processing_po_items', sa.Column('gsm', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('processing_po_items', sa.Column('lot_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('processing_po_items', sa.Column('qty', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=True))
    op.add_column('processing_po_items', sa.Column('uom', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('processing_po_items', sa.Column('fabric_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('processing_po_items', sa.Column('width', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('processing_po_items', sa.Column('fabric_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.alter_column('party_master', 'credit_limit',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('party_master', 'cst_no',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('party_master', 'tin_no',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('party_master', 'pan_no',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('party_master', 'gst_no',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('party_master', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('party_master', 'currency',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('party_master', 'pin_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('packing_slips', 'status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.add_column('grey_yarn_delivery_items', sa.Column('lot_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('grey_yarn_delivery_items', sa.Column('yarn_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('grey_yarn_delivery_items', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'total_kgs',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'stock',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'color',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'count',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.add_column('grey_yarn_deliveries', sa.Column('sgst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('total_kgs', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('igst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('gross_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('net_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.create_foreign_key('grey_yarn_deliveries_party_id_fkey', 'grey_yarn_deliveries', 'party_master', ['party_id'], ['id'])
    op.alter_column('grey_yarn_deliveries', 'certificate_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'transport',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'order_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'design_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'delivery_mode',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'delivery_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.add_column('general_master', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('general_master', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('general_master', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('fabric_dyeing_pos', sa.Column('tax_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_eway_bills_id'), table_name='eway_bills')
    op.drop_index(op.f('ix_eway_bills_eway_bill_no'), table_name='eway_bills')
    op.create_unique_constraint('eway_bills_eway_bill_no_key', 'eway_bills', ['eway_bill_no'])
    op.drop_constraint(None, 'eway_bill_items', type_='foreignkey')
    op.create_foreign_key('eway_bill_items_bill_id_fkey', 'eway_bill_items', 'eway_bills', ['bill_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_eway_bill_items_id'), table_name='eway_bill_items')
    op.alter_column('eway_bill_items', 'bill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('dyed_yarn_received_items', sa.Column('delivery_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_received_items', sa.Column('received_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_dyed_yarn_received_receipt_no'), table_name='dyed_yarn_received')
    op.add_column('dyed_yarn_delivery_items', sa.Column('purchase_order_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_delivery_items', sa.Column('stock_qty', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.alter_column('dyed_yarn_delivery_items', 'stock',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('dyed_yarn_delivery_items', 'color',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('dyed_yarn_delivery_items', 'count',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.add_column('dyed_yarn_deliveries', sa.Column('buyer', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('delivery_challan_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('igst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('add_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('lr_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('cost', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('net_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('dispatch_from', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('expected_return_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('design_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('contact_person', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('balance_amount', sa.NUMERIC(precision=14, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('mobile_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('dc_no_alt', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('received_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('advance_received', sa.NUMERIC(precision=14, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('tds', sa.NUMERIC(precision=14, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('mobile_no', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('customer_po_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('company', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('dyeing_po_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('buyer_order', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('financial_year', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('total_delv_kgs', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('sgst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('dyeing_batch_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('processor_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('insurance', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('tcs', sa.NUMERIC(precision=14, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('total_rin_kgs', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('tax_value', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('branch', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_dyed_yarn_deliveries_delivery_no'), table_name='dyed_yarn_deliveries')
    op.drop_index(op.f('ix_dyed_yarn_deliveries_dc_no'), table_name='dyed_yarn_deliveries')
    op.create_index('ix_dyed_yarn_deliveries_dc_no', 'dyed_yarn_deliveries', ['dc_no'], unique=True)
    op.alter_column('dyed_yarn_deliveries', 'certificate_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('dyed_yarn_deliveries', 'delivery_time',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('dyed_yarn_deliveries', 'transport',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('dyed_yarn_deliveries', 'dc_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('despatch_planning', 'currency',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('despatch_planning', 'uom',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('despatch_planning', 'design_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.add_column('design_entry', sa.Column('grey_reed_add', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('4.0'), autoincrement=False, nullable=True))
    op.add_column('design_entry', sa.Column('fab_width_reed_add', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('4.0'), autoincrement=False, nullable=True))
    op.add_column('design_entry', sa.Column('glm', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('design_entry', sa.Column('reed_space', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('design_entry', sa.Column('gsm', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('design_entry', sa.Column('fabric_width_grey', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('design_entry', sa.Column('grey_reed', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('design_entry', sa.Column('onloom_reed', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('design_entry', sa.Column('onloom_pick', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('design_entry', sa.Column('reed_less', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('8.0'), autoincrement=False, nullable=True))
    op.add_column('design_entry', sa.Column('pick_less', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('4.0'), autoincrement=False, nullable=True))
    op.alter_column('design_entry', 'fabric_design_details',
               existing_type=sa.String(length=4000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('design_entry', 'yarn_details',
               existing_type=sa.String(length=4000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('cloth_purchase_pos', sa.Column('tax_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('buyer_orders', sa.Column('credit_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('buyer_order_items', 'currency',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('buyer_order_expenses', 'currency',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.create_table('yarn_purchase_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('po_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('yarn_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('count', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('lot_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('bags', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cones', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_kgs', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['yarn_purchase_orders.id'], name='yarn_purchase_items_po_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='yarn_purchase_items_pkey')
    )
    op.create_index('ix_yarn_purchase_items_id', 'yarn_purchase_items', ['id'], unique=False)
    op.create_table('Stock_Ledger_Entry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('voucher_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('voucher_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('voucher_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('lot_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('colour', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('shade_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('qty_in', sa.NUMERIC(precision=14, scale=3), autoincrement=False, nullable=True),
    sa.Column('qty_out', sa.NUMERIC(precision=14, scale=3), autoincrement=False, nullable=True),
    sa.Column('balance_stock', sa.NUMERIC(precision=14, scale=3), autoincrement=False, nullable=True),
    sa.Column('ref_po', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ref_dc', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('godown', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('operator', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Stock_Ledger_Entry_pkey')
    )
    op.create_index('ix_Stock_Ledger_Entry_id', 'Stock_Ledger_Entry', ['id'], unique=False)
    op.create_table('loom_allocations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('loom_allocations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('loom_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('warp_ends', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weft_density', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fabric_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assigned_meters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('completed_meters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expected_finish_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('allocation_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['loom_id'], ['loom_master.id'], name='loom_allocations_loom_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='loom_allocations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_loom_allocations_id', 'loom_allocations', ['id'], unique=False)
    op.create_table('JobWork_Delivery_Header',
    sa.Column('DeliveryID', sa.INTEGER(), server_default=sa.text('nextval(\'"JobWork_Delivery_Header_DeliveryID_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('DeliveryNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('DCNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('DCDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('DeliveryDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('DeliveryType', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('DeliveryMode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('YarnDyeingPONo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ProcessorName', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('PartyName', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('OrderNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('RefNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('DesignNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Merchandiser', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('VehicleNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('DriverName', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('DriverMobile', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('TransportName', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('LRNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('GatePassNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('EWayBillNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('DispatchFromGodown', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('Remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('TotalOrderedQty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('TotalPrevDeliveredQty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('TotalCurrentDeliveryQty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('TotalBalanceQty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('TotalBags', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TotalCones', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TotalGrossWeight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('TotalNetWeight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('FreightCharges', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('LoadingCharges', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('UnloadingCharges', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('InsuranceCharges', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('OtherCharges', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('TransportRemarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('TaxableAmount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('SGSTPct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('SGSTAmount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('CGSTPct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('CGSTAmount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('IGSTPct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('IGSTAmount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('TotalGST', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('GrossAmount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('Discount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('RoundOff', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('GrandTotal', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('Advance', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('Balance', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('DeliveryStatus', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('Company', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Branch', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('FinancialYear', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ExpectedReturnDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('PreparedBy', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('DyeingPODate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('ProcessorAddress', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ContactPerson', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('MobileNumber', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Buyer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('BuyerOrder', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('DispatchThrough', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('FreightType', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('CompanyID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('BranchID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('POID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ProcessorID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('BuyerID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('BuyerOrderID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TransportID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Freight', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('TaxAmount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('NetAmount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('Status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('CreatedBy', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('CreatedDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('ApprovedBy', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ApprovedDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('DeliveryID', name='JobWork_Delivery_Header_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_JobWork_Delivery_Header_DeliveryNo', 'JobWork_Delivery_Header', ['DeliveryNo'], unique=True)
    op.create_index('ix_JobWork_Delivery_Header_DeliveryID', 'JobWork_Delivery_Header', ['DeliveryID'], unique=False)
    op.create_index('ix_JobWork_Delivery_Header_DCNo', 'JobWork_Delivery_Header', ['DCNo'], unique=False)
    op.create_table('production_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('allocation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meters_produced', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('downtime_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['loom_allocations.id'], name='production_logs_allocation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='production_logs_pkey')
    )
    op.create_index('ix_production_logs_id', 'production_logs', ['id'], unique=False)
    op.create_table('operator_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('operator_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('skill_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assigned_loom', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assigned_shift', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('join_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('contact_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='operator_master_pkey')
    )
    op.create_index('ix_operator_master_operator_id', 'operator_master', ['operator_id'], unique=True)
    op.create_index('ix_operator_master_id', 'operator_master', ['id'], unique=False)
    op.create_table('loom_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('loom_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('loom_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('installation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('capacity_per_day', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('running_speed_per_hr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('efficiency_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reed_width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_ends', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_service_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_service_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_warp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_weft', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='loom_master_pkey')
    )
    op.create_index('ix_loom_master_loom_name', 'loom_master', ['loom_name'], unique=True)
    op.create_index('ix_loom_master_id', 'loom_master', ['id'], unique=False)
    op.create_table('JobWork_Delivery_Detail',
    sa.Column('DetailID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('DeliveryID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SPNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('DesignNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('YarnType', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('YarnCount', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Ply', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('Colour', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ShadeNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('LotNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('BatchNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('OrderedQty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('PrevDeliveredQty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('BalanceQty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('CurrentDeliveryQty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('NoOfBags', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoOfCones', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('GrossWeight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('TareWeight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('NetWeight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('Rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('Amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('Remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('POItemNo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('YarnDescription', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ConeType', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('YarnBrand', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('AvailableStock', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('WarpQty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('WeftQty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('TotalPOQty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('AlreadyDelivered', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('TolerancePct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('DesignID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('YarnID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ColorID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ShadeID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LotID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('DispatchQty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('BagCount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ConeCount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['DeliveryID'], ['JobWork_Delivery_Header.DeliveryID'], name='JobWork_Delivery_Detail_DeliveryID_fkey'),
    sa.PrimaryKeyConstraint('DetailID', name='JobWork_Delivery_Detail_pkey')
    )
    op.create_index('ix_JobWork_Delivery_Detail_DetailID', 'JobWork_Delivery_Detail', ['DetailID'], unique=False)
    # ### end Alembic commands ###
