"""Add massive Buyer Order fields

Revision ID: 261ad5b3839d
Revises: 053cae0add22
Create Date: 2026-05-26 16:01:55.571095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261ad5b3839d'
down_revision: Union[str, None] = '053cae0add22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_general_master_category', table_name='general_master')
    op.drop_index('ix_general_master_id', table_name='general_master')
    op.drop_table('general_master')
    op.add_column('buyer_order_items', sa.Column('point_of_contact', sa.String(length=150), nullable=True))
    op.add_column('buyer_order_items', sa.Column('total_mtr_yard', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('buyer_order_items', sa.Column('sample_mtr', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('buyer_order_items', sa.Column('short_no', sa.String(length=50), nullable=True))
    op.add_column('buyer_order_items', sa.Column('gry_construction', sa.String(length=150), nullable=True))
    op.add_column('buyer_order_items', sa.Column('construction', sa.String(length=150), nullable=True))
    op.add_column('buyer_order_items', sa.Column('weaving_type', sa.String(length=50), nullable=True))
    op.add_column('buyer_order_items', sa.Column('pick_on_table', sa.Integer(), nullable=True))
    op.add_column('buyer_order_items', sa.Column('print_name', sa.String(length=100), nullable=True))
    op.add_column('buyer_order_items', sa.Column('finish_reed', sa.Integer(), nullable=True))
    op.add_column('buyer_order_items', sa.Column('finish_pick', sa.Integer(), nullable=True))
    op.add_column('buyer_order_items', sa.Column('finish_width', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('buyer_order_items', sa.Column('cuttable_width', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('buyer_order_items', sa.Column('pattern', sa.String(length=50), nullable=True))
    op.add_column('buyer_order_items', sa.Column('packing_type', sa.String(length=50), nullable=True))
    op.add_column('buyer_order_items', sa.Column('loom_type', sa.String(length=50), nullable=True))
    op.add_column('buyer_order_items', sa.Column('insurance', sa.String(length=10), nullable=True))
    op.add_column('buyer_order_items', sa.Column('packing_charge', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('buyer_order_items', sa.Column('end_use', sa.String(length=100), nullable=True))
    op.add_column('buyer_order_items', sa.Column('season', sa.String(length=50), nullable=True))
    op.add_column('buyer_order_items', sa.Column('party_comment', sa.Text(), nullable=True))
    op.add_column('buyer_order_items', sa.Column('fabric_content', sa.String(length=150), nullable=True))
    op.add_column('buyer_order_items', sa.Column('development_id', sa.String(length=50), nullable=True))
    op.add_column('buyer_order_items', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('buyer_order_items', sa.Column('combo', sa.String(length=50), nullable=True))
    op.add_column('buyer_order_items', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('buyer_order_items', sa.Column('pc_type', sa.String(length=50), nullable=True))
    op.add_column('buyer_order_items', sa.Column('gsm', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('buyer_order_items', sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('buyer_order_items', sa.Column('gst_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('buyer_order_items', sa.Column('gst_rate', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('buyer_order_items', sa.Column('image_design_path', sa.String(length=255), nullable=True))
    op.add_column('buyer_orders', sa.Column('buyer_name', sa.String(length=255), nullable=True))
    op.add_column('buyer_orders', sa.Column('commission_type', sa.String(length=50), nullable=True))
    op.add_column('buyer_orders', sa.Column('order_taken_by', sa.String(length=150), nullable=True))
    op.add_column('buyer_orders', sa.Column('regular_special', sa.String(length=50), nullable=True))
    op.add_column('buyer_orders', sa.Column('due_30_days', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('buyer_orders', sa.Column('status_remark', sa.Text(), nullable=True))
    op.add_column('buyer_orders', sa.Column('max_crd_days', sa.Integer(), nullable=True))
    op.add_column('buyer_orders', sa.Column('po_credit', sa.Integer(), nullable=True))
    op.add_column('buyer_orders', sa.Column('po_max_crd', sa.Integer(), nullable=True))
    op.add_column('buyer_orders', sa.Column('bill_credit', sa.Integer(), nullable=True))
    op.add_column('buyer_orders', sa.Column('payment_detail', sa.Text(), nullable=True))
    op.add_column('buyer_orders', sa.Column('payment_file_path', sa.String(length=255), nullable=True))
    op.add_column('buyer_orders', sa.Column('party_terms', sa.String(length=100), nullable=True))
    op.add_column('buyer_orders', sa.Column('party_comp_date', sa.Date(), nullable=True))
    op.add_column('buyer_orders', sa.Column('exfactory_date', sa.Date(), nullable=True))
    op.add_column('buyer_orders', sa.Column('delivery_starting', sa.Date(), nullable=True))
    op.add_column('buyer_orders', sa.Column('delivery_at', sa.String(length=150), nullable=True))
    op.add_column('buyer_orders', sa.Column('desp_mtr_min', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('buyer_orders', sa.Column('desp_mtr_max', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('buyer_orders', sa.Column('process_sequence', sa.Text(), nullable=True))
    op.add_column('buyer_orders', sa.Column('process_instruction', sa.Text(), nullable=True))
    op.add_column('buyer_orders', sa.Column('email_to', sa.Text(), nullable=True))
    op.add_column('buyer_orders', sa.Column('email_cc', sa.Text(), nullable=True))
    op.add_column('buyer_orders', sa.Column('yarn_instruction', sa.Text(), nullable=True))
    op.add_column('buyer_orders', sa.Column('prod_instruction', sa.Text(), nullable=True))
    op.add_column('buyer_orders', sa.Column('delivery_instruction', sa.Text(), nullable=True))
    op.drop_column('buyer_orders', 'credit_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyer_orders', sa.Column('credit_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('buyer_orders', 'delivery_instruction')
    op.drop_column('buyer_orders', 'prod_instruction')
    op.drop_column('buyer_orders', 'yarn_instruction')
    op.drop_column('buyer_orders', 'email_cc')
    op.drop_column('buyer_orders', 'email_to')
    op.drop_column('buyer_orders', 'process_instruction')
    op.drop_column('buyer_orders', 'process_sequence')
    op.drop_column('buyer_orders', 'desp_mtr_max')
    op.drop_column('buyer_orders', 'desp_mtr_min')
    op.drop_column('buyer_orders', 'delivery_at')
    op.drop_column('buyer_orders', 'delivery_starting')
    op.drop_column('buyer_orders', 'exfactory_date')
    op.drop_column('buyer_orders', 'party_comp_date')
    op.drop_column('buyer_orders', 'party_terms')
    op.drop_column('buyer_orders', 'payment_file_path')
    op.drop_column('buyer_orders', 'payment_detail')
    op.drop_column('buyer_orders', 'bill_credit')
    op.drop_column('buyer_orders', 'po_max_crd')
    op.drop_column('buyer_orders', 'po_credit')
    op.drop_column('buyer_orders', 'max_crd_days')
    op.drop_column('buyer_orders', 'status_remark')
    op.drop_column('buyer_orders', 'due_30_days')
    op.drop_column('buyer_orders', 'regular_special')
    op.drop_column('buyer_orders', 'order_taken_by')
    op.drop_column('buyer_orders', 'commission_type')
    op.drop_column('buyer_orders', 'buyer_name')
    op.drop_column('buyer_order_items', 'image_design_path')
    op.drop_column('buyer_order_items', 'gst_rate')
    op.drop_column('buyer_order_items', 'gst_pct')
    op.drop_column('buyer_order_items', 'price')
    op.drop_column('buyer_order_items', 'gsm')
    op.drop_column('buyer_order_items', 'pc_type')
    op.drop_column('buyer_order_items', 'currency')
    op.drop_column('buyer_order_items', 'combo')
    op.drop_column('buyer_order_items', 'country')
    op.drop_column('buyer_order_items', 'development_id')
    op.drop_column('buyer_order_items', 'fabric_content')
    op.drop_column('buyer_order_items', 'party_comment')
    op.drop_column('buyer_order_items', 'season')
    op.drop_column('buyer_order_items', 'end_use')
    op.drop_column('buyer_order_items', 'packing_charge')
    op.drop_column('buyer_order_items', 'insurance')
    op.drop_column('buyer_order_items', 'loom_type')
    op.drop_column('buyer_order_items', 'packing_type')
    op.drop_column('buyer_order_items', 'pattern')
    op.drop_column('buyer_order_items', 'cuttable_width')
    op.drop_column('buyer_order_items', 'finish_width')
    op.drop_column('buyer_order_items', 'finish_pick')
    op.drop_column('buyer_order_items', 'finish_reed')
    op.drop_column('buyer_order_items', 'print_name')
    op.drop_column('buyer_order_items', 'pick_on_table')
    op.drop_column('buyer_order_items', 'weaving_type')
    op.drop_column('buyer_order_items', 'construction')
    op.drop_column('buyer_order_items', 'gry_construction')
    op.drop_column('buyer_order_items', 'short_no')
    op.drop_column('buyer_order_items', 'sample_mtr')
    op.drop_column('buyer_order_items', 'total_mtr_yard')
    op.drop_column('buyer_order_items', 'point_of_contact')
    op.create_table('general_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='general_master_pkey')
    )
    op.create_index('ix_general_master_id', 'general_master', ['id'], unique=False)
    op.create_index('ix_general_master_category', 'general_master', ['category'], unique=False)
    # ### end Alembic commands ###
