"""Add warp and weft to loom master

Revision ID: 32a0d67ecf1d
Revises: 0cfc0af9f126
Create Date: 2026-06-12 12:35:52.025787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32a0d67ecf1d'
down_revision: Union[str, None] = '0cfc0af9f126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quotations_id', table_name='quotations')
    op.drop_index('ix_quotations_quotation_no', table_name='quotations')
    op.drop_table('quotations')
    op.drop_index('ix_inquiries_id', table_name='inquiries')
    op.drop_index('ix_inquiries_inquiry_no', table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index('ix_company_settings_id', table_name='company_settings')
    op.drop_table('company_settings')
    op.drop_index('ix_leads_email', table_name='leads')
    op.drop_index('ix_leads_id', table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_tasks_id', table_name='tasks')
    op.drop_table('tasks')
    op.alter_column('buyer_order_expenses', 'currency',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('buyer_order_items', 'currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('buyer_order_items', 'certifications')
    op.drop_column('buyer_order_items', 'yarn_count')
    op.drop_column('buyer_orders', 'bill_of_lading_no')
    op.drop_column('buyer_orders', 'amendments')
    op.drop_column('buyer_orders', 'insurance_amount')
    op.drop_column('buyer_orders', 'bill_of_lading_date')
    op.drop_column('buyer_orders', 'packing_amount')
    op.drop_column('buyer_orders', 'shipping_bill_no')
    op.drop_column('buyer_orders', 'lc_expiry_date')
    op.drop_column('buyer_orders', 'container_no')
    op.drop_column('buyer_orders', 'seal_no')
    op.drop_column('buyer_orders', 'shipping_bill_date')
    op.drop_column('buyer_orders', 'proforma_invoice_no')
    op.drop_column('buyer_orders', 'lc_no')
    op.drop_column('buyer_orders', 'export_order_no')
    op.drop_column('buyer_orders', 'freight_amount')
    op.alter_column('despatch_planning', 'point_of_contact',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('despatch_planning', 'incoterm')
    op.drop_column('despatch_planning', 'etd')
    op.drop_column('despatch_planning', 'freight_forwarder')
    op.drop_column('despatch_planning', 'eta')
    op.drop_column('despatch_planning', 'vessel_flight_name')
    op.drop_column('despatch_planning', 'cha_name')
    op.alter_column('party_master', 'currency',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('party_master', 'buyer_country_region')
    op.drop_column('party_master', 'preferred_port')
    op.drop_column('party_master', 'preferred_payment_terms')
    op.drop_column('party_master', 'product_interest')
    op.drop_column('party_master', 'currency_preference')
    op.alter_column('sales_invoices', 'currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_invoices', 'currency',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.add_column('party_master', sa.Column('currency_preference', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('party_master', sa.Column('product_interest', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('party_master', sa.Column('preferred_payment_terms', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('party_master', sa.Column('preferred_port', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('party_master', sa.Column('buyer_country_region', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('party_master', 'currency',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.add_column('despatch_planning', sa.Column('cha_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('despatch_planning', sa.Column('vessel_flight_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('despatch_planning', sa.Column('eta', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('despatch_planning', sa.Column('freight_forwarder', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('despatch_planning', sa.Column('etd', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('despatch_planning', sa.Column('incoterm', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('despatch_planning', 'point_of_contact',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.add_column('buyer_orders', sa.Column('freight_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('buyer_orders', sa.Column('export_order_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('buyer_orders', sa.Column('lc_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('buyer_orders', sa.Column('proforma_invoice_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('buyer_orders', sa.Column('shipping_bill_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('buyer_orders', sa.Column('seal_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('buyer_orders', sa.Column('container_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('buyer_orders', sa.Column('lc_expiry_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('buyer_orders', sa.Column('shipping_bill_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('buyer_orders', sa.Column('packing_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('buyer_orders', sa.Column('bill_of_lading_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('buyer_orders', sa.Column('insurance_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('buyer_orders', sa.Column('amendments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('buyer_orders', sa.Column('bill_of_lading_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('buyer_order_items', sa.Column('yarn_count', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('buyer_order_items', sa.Column('certifications', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.alter_column('buyer_order_items', 'currency',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('buyer_order_expenses', 'currency',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assigned_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('related_order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('related_inquiry_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['employees.id'], name='tasks_assigned_to_id_fkey'),
    sa.ForeignKeyConstraint(['related_inquiry_id'], ['inquiries.id'], name='tasks_related_inquiry_id_fkey'),
    sa.ForeignKeyConstraint(['related_order_id'], ['buyer_orders.id'], name='tasks_related_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tasks_pkey')
    )
    op.create_index('ix_tasks_id', 'tasks', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('leads_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('assigned_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['employees.id'], name='leads_assigned_to_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='leads_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_leads_id', 'leads', ['id'], unique=False)
    op.create_index('ix_leads_email', 'leads', ['email'], unique=True)
    op.create_table('company_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gstin', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pan_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('pin_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ifsc_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='company_settings_pkey')
    )
    op.create_index('ix_company_settings_id', 'company_settings', ['id'], unique=False)
    op.create_table('inquiries',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('inquiries_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('inquiry_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('required_product', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('specifications', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('uom', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('expected_delivery_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('assigned_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['employees.id'], name='inquiries_assigned_to_id_fkey'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name='inquiries_lead_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='inquiries_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_inquiries_inquiry_no', 'inquiries', ['inquiry_no'], unique=True)
    op.create_index('ix_inquiries_id', 'inquiries', ['id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quotation_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('inquiry_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('valid_until', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('shipping_term', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pdf_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], name='quotations_inquiry_id_fkey'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name='quotations_lead_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='quotations_pkey')
    )
    op.create_index('ix_quotations_quotation_no', 'quotations', ['quotation_no'], unique=True)
    op.create_index('ix_quotations_id', 'quotations', ['id'], unique=False)
    # ### end Alembic commands ###
