"""Add warehouse material models

Revision ID: 384e950e84bf
Revises: 1fb5ec81541e
Create Date: 2026-07-15 12:58:50.128518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '384e950e84bf'
down_revision: Union[str, None] = '1fb5ec81541e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stores_material_requests_id', table_name='stores_material_requests')
    op.drop_index('ix_stores_material_requests_request_no', table_name='stores_material_requests')
    op.drop_table('stores_material_requests')
    op.drop_index('ix_stores_issue_to_department_items_id', table_name='stores_issue_to_department_items')
    op.drop_table('stores_issue_to_department_items')
    op.drop_index('ix_stores_stock_adjustments_adjustment_no', table_name='stores_stock_adjustments')
    op.drop_index('ix_stores_stock_adjustments_id', table_name='stores_stock_adjustments')
    op.drop_table('stores_stock_adjustments')
    op.drop_index('ix_stationary_materials_id', table_name='stationary_materials')
    op.drop_index('ix_stationary_materials_item_code', table_name='stationary_materials')
    op.drop_table('stationary_materials')
    op.drop_index('ix_stores_purchase_orders_id', table_name='stores_purchase_orders')
    op.drop_index('ix_stores_purchase_orders_po_no', table_name='stores_purchase_orders')
    op.drop_table('stores_purchase_orders')
    op.drop_index('ix_stationary_grn_items_id', table_name='stationary_grn_items')
    op.drop_table('stationary_grn_items')
    op.drop_index('ix_stores_returnable_dc_items_id', table_name='stores_returnable_dc_items')
    op.drop_table('stores_returnable_dc_items')
    op.drop_index('ix_stores_issue_to_departments_id', table_name='stores_issue_to_departments')
    op.drop_index('ix_stores_issue_to_departments_issue_no', table_name='stores_issue_to_departments')
    op.drop_table('stores_issue_to_departments')
    op.drop_index('ix_stores_vendor_quotations_id', table_name='stores_vendor_quotations')
    op.drop_index('ix_stores_vendor_quotations_quote_no', table_name='stores_vendor_quotations')
    op.drop_table('stores_vendor_quotations')
    op.drop_index('ix_production_logs_id', table_name='production_logs')
    op.drop_table('production_logs')
    op.drop_index('ix_operator_master_id', table_name='operator_master')
    op.drop_index('ix_operator_master_operator_id', table_name='operator_master')
    op.drop_table('operator_master')
    op.drop_index('ix_stationary_stock_issues_id', table_name='stationary_stock_issues')
    op.drop_index('ix_stationary_stock_issues_issue_no', table_name='stationary_stock_issues')
    op.drop_table('stationary_stock_issues')
    op.drop_index('ix_stores_subcategories_id', table_name='stores_subcategories')
    op.drop_index('ix_stores_subcategories_subcategory_code', table_name='stores_subcategories')
    op.drop_table('stores_subcategories')
    op.drop_index('ix_stores_categories_category_code', table_name='stores_categories')
    op.drop_index('ix_stores_categories_category_name', table_name='stores_categories')
    op.drop_index('ix_stores_categories_id', table_name='stores_categories')
    op.drop_table('stores_categories')
    op.drop_index('ix_stationary_categories_id', table_name='stationary_categories')
    op.drop_index('ix_stationary_categories_name', table_name='stationary_categories')
    op.drop_table('stationary_categories')
    op.drop_index('ix_stores_warehouses_id', table_name='stores_warehouses')
    op.drop_index('ix_stores_warehouses_warehouse_code', table_name='stores_warehouses')
    op.drop_table('stores_warehouses')
    op.drop_index('ix_stationary_racks_id', table_name='stationary_racks')
    op.drop_table('stationary_racks')
    op.drop_index('ix_stationary_stock_issue_items_id', table_name='stationary_stock_issue_items')
    op.drop_table('stationary_stock_issue_items')
    op.drop_index('ix_stationary_stock_id', table_name='stationary_stock')
    op.drop_table('stationary_stock')
    op.drop_index('ix_vendors_vendor_id', table_name='vendors')
    op.drop_index('ix_vendors_vendor_name', table_name='vendors')
    op.drop_table('vendors')
    op.drop_index('ix_stores_stock_adjustment_items_id', table_name='stores_stock_adjustment_items')
    op.drop_table('stores_stock_adjustment_items')
    op.drop_index('ix_loom_master_id', table_name='loom_master')
    op.drop_index('ix_loom_master_loom_name', table_name='loom_master')
    op.drop_table('loom_master')
    op.drop_index('ix_stores_cost_centers_code', table_name='stores_cost_centers')
    op.drop_index('ix_stores_cost_centers_id', table_name='stores_cost_centers')
    op.drop_table('stores_cost_centers')
    op.drop_index('ix_stationary_grn_grn_no', table_name='stationary_grn')
    op.drop_index('ix_stationary_grn_id', table_name='stationary_grn')
    op.drop_table('stationary_grn')
    op.drop_index('ix_quotation_headers_quotation_id', table_name='quotation_headers')
    op.drop_table('quotation_headers')
    op.drop_index('ix_stores_vendor_quotation_items_id', table_name='stores_vendor_quotation_items')
    op.drop_table('stores_vendor_quotation_items')
    op.drop_index('ix_stores_departments_department_code', table_name='stores_departments')
    op.drop_index('ix_stores_departments_department_name', table_name='stores_departments')
    op.drop_index('ix_stores_departments_id', table_name='stores_departments')
    op.drop_table('stores_departments')
    op.drop_index('ix_stores_store_transfer_items_id', table_name='stores_store_transfer_items')
    op.drop_table('stores_store_transfer_items')
    op.drop_index('ix_stores_budgets_budget_code', table_name='stores_budgets')
    op.drop_index('ix_stores_budgets_id', table_name='stores_budgets')
    op.drop_table('stores_budgets')
    op.drop_index('ix_stores_purchase_requisitions_id', table_name='stores_purchase_requisitions')
    op.drop_index('ix_stores_purchase_requisitions_pr_number', table_name='stores_purchase_requisitions')
    op.drop_table('stores_purchase_requisitions')
    op.drop_index('ix_stores_store_transfers_id', table_name='stores_store_transfers')
    op.drop_index('ix_stores_store_transfers_transfer_no', table_name='stores_store_transfers')
    op.drop_table('stores_store_transfers')
    op.drop_index('ix_stores_stock_inward_items_id', table_name='stores_stock_inward_items')
    op.drop_table('stores_stock_inward_items')
    op.drop_index('ix_stores_purchase_requisition_items_id', table_name='stores_purchase_requisition_items')
    op.drop_table('stores_purchase_requisition_items')
    op.drop_index('ix_stationary_bins_id', table_name='stationary_bins')
    op.drop_table('stationary_bins')
    op.drop_index('ix_stationary_stock_ledger_id', table_name='stationary_stock_ledger')
    op.drop_table('stationary_stock_ledger')
    op.drop_index('ix_stationary_uoms_id', table_name='stationary_uoms')
    op.drop_index('ix_stationary_uoms_name', table_name='stationary_uoms')
    op.drop_table('stationary_uoms')
    op.drop_index('ix_loom_allocations_id', table_name='loom_allocations')
    op.drop_table('loom_allocations')
    op.drop_index('ix_stores_stock_inwards_grn_no', table_name='stores_stock_inwards')
    op.drop_index('ix_stores_stock_inwards_id', table_name='stores_stock_inwards')
    op.drop_table('stores_stock_inwards')
    op.drop_index('ix_stores_return_to_store_items_id', table_name='stores_return_to_store_items')
    op.drop_table('stores_return_to_store_items')
    op.drop_index('ix_stores_pr_approval_history_id', table_name='stores_pr_approval_history')
    op.drop_table('stores_pr_approval_history')
    op.drop_index('ix_quotation_line_items_line_item_id', table_name='quotation_line_items')
    op.drop_table('quotation_line_items')
    op.drop_index('ix_stationary_warehouses_code', table_name='stationary_warehouses')
    op.drop_index('ix_stationary_warehouses_id', table_name='stationary_warehouses')
    op.drop_table('stationary_warehouses')
    op.drop_index('ix_stores_purchase_order_items_id', table_name='stores_purchase_order_items')
    op.drop_table('stores_purchase_order_items')
    op.drop_index('ix_stores_uoms_id', table_name='stores_uoms')
    op.drop_index('ix_stores_uoms_uom_code', table_name='stores_uoms')
    op.drop_table('stores_uoms')
    op.drop_index('ix_stores_vendors_id', table_name='stores_vendors')
    op.drop_index('ix_stores_vendors_vendor_code', table_name='stores_vendors')
    op.drop_index('ix_stores_vendors_vendor_name', table_name='stores_vendors')
    op.drop_table('stores_vendors')
    op.drop_index('ix_stores_items_id', table_name='stores_items')
    op.drop_index('ix_stores_items_item_code', table_name='stores_items')
    op.drop_index('ix_stores_items_item_name', table_name='stores_items')
    op.drop_table('stores_items')
    op.drop_index('ix_stores_return_to_stores_id', table_name='stores_return_to_stores')
    op.drop_index('ix_stores_return_to_stores_return_no', table_name='stores_return_to_stores')
    op.drop_table('stores_return_to_stores')
    op.drop_index('ix_stores_returnable_dcs_dc_no', table_name='stores_returnable_dcs')
    op.drop_index('ix_stores_returnable_dcs_id', table_name='stores_returnable_dcs')
    op.drop_table('stores_returnable_dcs')
    op.drop_column('cloth_inward_items', 'width')
    op.drop_column('cloth_inwards', 'beam_return_kgs')
    op.drop_column('cloth_inwards', 'weft_return_kgs')
    op.drop_column('cloth_inwards', 'warp_issued_kgs')
    op.drop_column('cloth_inwards', 'weft_issued_kgs')
    op.drop_column('cloth_inwards', 'total_weight')
    op.drop_column('cloth_inwards', 'weaving_waste_kgs')
    op.drop_column('cloth_inwards', 'our_delivery_ref')
    op.drop_column('cloth_inwards', 'weaving_waste_pct')
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    op.drop_column('fabric_dyeing_pos', 'fabric_receipt_id')
    op.drop_column('on_table_checking', 'qc_name')
    op.drop_column('routes', 'toll_charges')
    op.drop_column('routes', 'avg_speed')
    op.drop_column('routes', 'difficulty')
    op.drop_column('routes', 'road_condition')
    op.drop_column('warp_deliveries', 'net_amount')
    op.drop_column('warp_deliveries', 'terms_conditions')
    op.drop_column('warp_deliveries', 'gross_amt')
    op.drop_column('warp_deliveries', 'sgst_pct')
    op.drop_column('warp_deliveries', 'igst_amount')
    op.drop_column('warp_deliveries', 'cgst_pct')
    op.drop_column('warp_deliveries', 'igst_pct')
    op.drop_column('warp_deliveries', 'tax_type')
    op.drop_column('warp_deliveries', 'cgst_amount')
    op.drop_column('warp_deliveries', 'sgst_amount')
    op.drop_column('weaving_pos', 'shrinkage')
    op.drop_column('weaving_pos', 'finished_width')
    op.drop_column('weaving_pos', 'no_repeat')
    op.drop_column('weaving_pos', 'pick')
    op.drop_column('weaving_pos', 'warp_width')
    op.drop_column('weaving_pos', 'loom_type')
    op.drop_column('weaving_pos', 'fabric')
    op.drop_column('weaving_pos', 'fabric_width')
    op.drop_column('weaving_pos', 'wages_mtr_kgs')
    op.drop_column('weaving_pos', 'crimp_pct')
    op.drop_column('weaving_pos', 'selected_count')
    op.drop_column('weaving_pos', 'delivery_at')
    op.drop_column('weaving_pos', 'warp_ends')
    op.drop_column('weaving_pos', 'merchandiser')
    op.drop_column('weaving_pos', 'salvage_waste_pct')
    op.drop_column('weaving_pos', 'certificate_type')
    op.drop_column('weaving_pos', 'design_color')
    op.drop_column('weaving_pos', 'warp_meters')
    op.drop_column('weaving_pos', 'weft_meters')
    op.drop_column('weaving_pos', 'warp_isu_mtrs')
    op.drop_column('weaving_pos', 'delivery_command')
    op.drop_column('weaving_pos', 'fabric_type')
    op.drop_column('weaving_pos', 'weaving_type')
    op.drop_column('weaving_pos', 'order_type')
    op.drop_column('weaving_pos', 'cooly_pick')
    op.drop_column('weaving_pos', 'cooly_mtr')
    op.drop_column('weaving_pos', 'reed')
    op.drop_column('weaving_pos', 'warp_issued')
    op.drop_column('weaving_pos', 'v_order_mtrs')
    op.drop_column('weaving_pos', 'min_mtrs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weaving_pos', sa.Column('min_mtrs', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('v_order_mtrs', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('warp_issued', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('reed', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('cooly_mtr', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('cooly_pick', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('order_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('weaving_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('fabric_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('delivery_command', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('warp_isu_mtrs', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('weft_meters', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('warp_meters', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('design_color', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('certificate_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('salvage_waste_pct', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('merchandiser', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('warp_ends', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('delivery_at', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('selected_count', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('crimp_pct', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('wages_mtr_kgs', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('fabric_width', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('fabric', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('loom_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('warp_width', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('pick', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('no_repeat', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('finished_width', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('weaving_pos', sa.Column('shrinkage', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('warp_deliveries', sa.Column('sgst_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('warp_deliveries', sa.Column('cgst_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('warp_deliveries', sa.Column('tax_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('warp_deliveries', sa.Column('igst_pct', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('warp_deliveries', sa.Column('cgst_pct', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('warp_deliveries', sa.Column('igst_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('warp_deliveries', sa.Column('sgst_pct', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('warp_deliveries', sa.Column('gross_amt', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('warp_deliveries', sa.Column('terms_conditions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('warp_deliveries', sa.Column('net_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('routes', sa.Column('road_condition', sa.VARCHAR(length=50), server_default=sa.text("'Good'::character varying"), autoincrement=False, nullable=True))
    op.add_column('routes', sa.Column('difficulty', sa.VARCHAR(length=50), server_default=sa.text("'Medium'::character varying"), autoincrement=False, nullable=True))
    op.add_column('routes', sa.Column('avg_speed', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('routes', sa.Column('toll_charges', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('on_table_checking', sa.Column('qc_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('fabric_dyeing_pos', sa.Column('fabric_receipt_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.add_column('cloth_inwards', sa.Column('weaving_waste_pct', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('cloth_inwards', sa.Column('our_delivery_ref', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('cloth_inwards', sa.Column('weaving_waste_kgs', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('cloth_inwards', sa.Column('total_weight', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('cloth_inwards', sa.Column('weft_issued_kgs', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('cloth_inwards', sa.Column('warp_issued_kgs', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('cloth_inwards', sa.Column('weft_return_kgs', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('cloth_inwards', sa.Column('beam_return_kgs', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('cloth_inward_items', sa.Column('width', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_table('stores_returnable_dcs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stores_returnable_dcs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('dc_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('issue_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expected_return_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('issued_to_department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('issued_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['stores_issue_to_departments.id'], name='stores_returnable_dcs_issue_id_fkey'),
    sa.ForeignKeyConstraint(['issued_by_id'], ['employees.id'], name='stores_returnable_dcs_issued_by_id_fkey'),
    sa.ForeignKeyConstraint(['issued_to_department_id'], ['stores_departments.id'], name='stores_returnable_dcs_issued_to_department_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_returnable_dcs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stores_returnable_dcs_id', 'stores_returnable_dcs', ['id'], unique=False)
    op.create_index('ix_stores_returnable_dcs_dc_no', 'stores_returnable_dcs', ['dc_no'], unique=True)
    op.create_table('stores_return_to_stores',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stores_return_to_stores_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('return_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('return_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('returned_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('received_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['stores_issue_to_departments.id'], name='stores_return_to_stores_issue_id_fkey'),
    sa.ForeignKeyConstraint(['received_by_id'], ['employees.id'], name='stores_return_to_stores_received_by_id_fkey'),
    sa.ForeignKeyConstraint(['returned_by_id'], ['employees.id'], name='stores_return_to_stores_returned_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_return_to_stores_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stores_return_to_stores_return_no', 'stores_return_to_stores', ['return_no'], unique=True)
    op.create_index('ix_stores_return_to_stores_id', 'stores_return_to_stores', ['id'], unique=False)
    op.create_table('stores_items',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stores_items_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uom_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('minimum_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('maximum_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reorder_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('purchase_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('current_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('warehouse', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('zone', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rack', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('shelf', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bin', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('barcode', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['stores_categories.id'], name='stores_items_category_id_fkey'),
    sa.ForeignKeyConstraint(['department_id'], ['stores_departments.id'], name='stores_items_department_id_fkey'),
    sa.ForeignKeyConstraint(['uom_id'], ['stores_uoms.id'], name='stores_items_uom_id_fkey'),
    sa.ForeignKeyConstraint(['vendor_id'], ['stores_vendors.id'], name='stores_items_vendor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_items_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stores_items_item_name', 'stores_items', ['item_name'], unique=False)
    op.create_index('ix_stores_items_item_code', 'stores_items', ['item_code'], unique=True)
    op.create_index('ix_stores_items_id', 'stores_items', ['id'], unique=False)
    op.create_table('stores_vendors',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stores_vendors_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('vendor_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('vendor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_person', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('gst_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payment_terms', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vendor_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stores_vendors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stores_vendors_vendor_name', 'stores_vendors', ['vendor_name'], unique=False)
    op.create_index('ix_stores_vendors_vendor_code', 'stores_vendors', ['vendor_code'], unique=True)
    op.create_index('ix_stores_vendors_id', 'stores_vendors', ['id'], unique=False)
    op.create_table('stores_uoms',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stores_uoms_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('uom_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('uom_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stores_uoms_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stores_uoms_uom_code', 'stores_uoms', ['uom_code'], unique=True)
    op.create_index('ix_stores_uoms_id', 'stores_uoms', ['id'], unique=False)
    op.create_table('stores_purchase_order_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('po_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uom_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('discount_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discount_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gst', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_with_gst', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['stores_categories.id'], name='stores_purchase_order_items_category_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['stores_items.id'], name='stores_purchase_order_items_item_id_fkey'),
    sa.ForeignKeyConstraint(['po_id'], ['stores_purchase_orders.id'], name='stores_purchase_order_items_po_id_fkey'),
    sa.ForeignKeyConstraint(['uom_id'], ['stores_uoms.id'], name='stores_purchase_order_items_uom_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_purchase_order_items_pkey')
    )
    op.create_index('ix_stores_purchase_order_items_id', 'stores_purchase_order_items', ['id'], unique=False)
    op.create_table('stationary_warehouses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stationary_warehouses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('branch', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('manager', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('capacity', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stationary_warehouses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stationary_warehouses_id', 'stationary_warehouses', ['id'], unique=False)
    op.create_index('ix_stationary_warehouses_code', 'stationary_warehouses', ['code'], unique=True)
    op.create_table('quotation_line_items',
    sa.Column('line_item_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quotation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gst_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation_headers.quotation_id'], name='quotation_line_items_quotation_id_fkey'),
    sa.PrimaryKeyConstraint('line_item_id', name='quotation_line_items_pkey')
    )
    op.create_index('ix_quotation_line_items_line_item_id', 'quotation_line_items', ['line_item_id'], unique=False)
    op.create_table('stores_pr_approval_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('approver_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('designation', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('stage', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('action_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['stores_purchase_requisitions.id'], name='stores_pr_approval_history_pr_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_pr_approval_history_pkey')
    )
    op.create_index('ix_stores_pr_approval_history_id', 'stores_pr_approval_history', ['id'], unique=False)
    op.create_table('stores_return_to_store_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('return_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uom_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_returned', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('condition', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['stores_categories.id'], name='stores_return_to_store_items_category_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['stores_items.id'], name='stores_return_to_store_items_item_id_fkey'),
    sa.ForeignKeyConstraint(['return_id'], ['stores_return_to_stores.id'], name='stores_return_to_store_items_return_id_fkey'),
    sa.ForeignKeyConstraint(['uom_id'], ['stores_uoms.id'], name='stores_return_to_store_items_uom_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_return_to_store_items_pkey')
    )
    op.create_index('ix_stores_return_to_store_items_id', 'stores_return_to_store_items', ['id'], unique=False)
    op.create_table('stores_stock_inwards',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stores_stock_inwards_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('grn_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('po_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inward_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('received_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inspected_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['inspected_by_id'], ['employees.id'], name='stores_stock_inwards_inspected_by_id_fkey'),
    sa.ForeignKeyConstraint(['po_id'], ['stores_purchase_orders.id'], name='stores_stock_inwards_po_id_fkey'),
    sa.ForeignKeyConstraint(['received_by_id'], ['employees.id'], name='stores_stock_inwards_received_by_id_fkey'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['stores_warehouses.id'], name='stores_stock_inwards_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_stock_inwards_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stores_stock_inwards_id', 'stores_stock_inwards', ['id'], unique=False)
    op.create_index('ix_stores_stock_inwards_grn_no', 'stores_stock_inwards', ['grn_no'], unique=True)
    op.create_table('loom_allocations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('loom_allocations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('loom_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('warp_ends', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weft_density', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fabric_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assigned_meters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('completed_meters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expected_finish_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('allocation_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['loom_id'], ['loom_master.id'], name='loom_allocations_loom_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='loom_allocations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_loom_allocations_id', 'loom_allocations', ['id'], unique=False)
    op.create_table('stationary_uoms',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stationary_uoms_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('decimal_precision', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stationary_uoms_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stationary_uoms_name', 'stationary_uoms', ['name'], unique=True)
    op.create_index('ix_stationary_uoms_id', 'stationary_uoms', ['id'], unique=False)
    op.create_table('stationary_stock_ledger',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('transaction_ref', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bin_id'], ['stationary_bins.id'], name='stationary_stock_ledger_bin_id_fkey'),
    sa.ForeignKeyConstraint(['material_id'], ['stationary_materials.id'], name='stationary_stock_ledger_material_id_fkey'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['stationary_warehouses.id'], name='stationary_stock_ledger_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stationary_stock_ledger_pkey')
    )
    op.create_index('ix_stationary_stock_ledger_id', 'stationary_stock_ledger', ['id'], unique=False)
    op.create_table('stationary_bins',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stationary_bins_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('rack_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('shelf', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rack_id'], ['stationary_racks.id'], name='stationary_bins_rack_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stationary_bins_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stationary_bins_id', 'stationary_bins', ['id'], unique=False)
    op.create_table('stores_purchase_requisition_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subcategory_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uom_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('estimated_unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gst', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('rack_bin', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('specification', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['stores_categories.id'], name='stores_purchase_requisition_items_category_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['stores_items.id'], name='stores_purchase_requisition_items_item_id_fkey'),
    sa.ForeignKeyConstraint(['pr_id'], ['stores_purchase_requisitions.id'], name='stores_purchase_requisition_items_pr_id_fkey'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['stores_subcategories.id'], name='stores_purchase_requisition_items_subcategory_id_fkey'),
    sa.ForeignKeyConstraint(['uom_id'], ['stores_uoms.id'], name='stores_purchase_requisition_items_uom_id_fkey'),
    sa.ForeignKeyConstraint(['vendor_id'], ['stores_vendors.id'], name='stores_purchase_requisition_items_vendor_id_fkey'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['stores_warehouses.id'], name='stores_purchase_requisition_items_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_purchase_requisition_items_pkey')
    )
    op.create_index('ix_stores_purchase_requisition_items_id', 'stores_purchase_requisition_items', ['id'], unique=False)
    op.create_table('stores_stock_inward_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grn_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uom_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ordered_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('received_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('variance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('inspection_status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('rack_bin', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('room', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rack', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rack_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['stores_categories.id'], name='stores_stock_inward_items_category_id_fkey'),
    sa.ForeignKeyConstraint(['grn_id'], ['stores_stock_inwards.id'], name='stores_stock_inward_items_grn_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['stores_items.id'], name='stores_stock_inward_items_item_id_fkey'),
    sa.ForeignKeyConstraint(['uom_id'], ['stores_uoms.id'], name='stores_stock_inward_items_uom_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_stock_inward_items_pkey')
    )
    op.create_index('ix_stores_stock_inward_items_id', 'stores_stock_inward_items', ['id'], unique=False)
    op.create_table('stores_store_transfers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stores_store_transfers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('transfer_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('source_warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('destination_warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transferred_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transfer_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['stores_warehouses.id'], name='stores_store_transfers_destination_warehouse_id_fkey'),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['stores_warehouses.id'], name='stores_store_transfers_source_warehouse_id_fkey'),
    sa.ForeignKeyConstraint(['transferred_by_id'], ['employees.id'], name='stores_store_transfers_transferred_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_store_transfers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stores_store_transfers_transfer_no', 'stores_store_transfers', ['transfer_no'], unique=True)
    op.create_index('ix_stores_store_transfers_id', 'stores_store_transfers', ['id'], unique=False)
    op.create_table('stores_purchase_requisitions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stores_purchase_requisitions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('pr_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('request_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('required_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('request_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost_center_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('branch_factory', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('delivery_warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('delivery_plant', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('delivery_department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delivery_address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('expected_delivery_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('budget_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['stores_budgets.id'], name='stores_purchase_requisitions_budget_id_fkey'),
    sa.ForeignKeyConstraint(['cost_center_id'], ['stores_cost_centers.id'], name='stores_purchase_requisitions_cost_center_id_fkey'),
    sa.ForeignKeyConstraint(['delivery_department_id'], ['stores_departments.id'], name='stores_purchase_requisitions_delivery_department_id_fkey'),
    sa.ForeignKeyConstraint(['delivery_warehouse_id'], ['stores_warehouses.id'], name='stores_purchase_requisitions_delivery_warehouse_id_fkey'),
    sa.ForeignKeyConstraint(['department_id'], ['stores_departments.id'], name='stores_purchase_requisitions_department_id_fkey'),
    sa.ForeignKeyConstraint(['requester_id'], ['employees.id'], name='stores_purchase_requisitions_requester_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_purchase_requisitions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stores_purchase_requisitions_pr_number', 'stores_purchase_requisitions', ['pr_number'], unique=True)
    op.create_index('ix_stores_purchase_requisitions_id', 'stores_purchase_requisitions', ['id'], unique=False)
    op.create_table('stores_budgets',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stores_budgets_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('budget_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('project_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cost_center_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('budget_available', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('budget_used', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cost_center_id'], ['stores_cost_centers.id'], name='stores_budgets_cost_center_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_budgets_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stores_budgets_id', 'stores_budgets', ['id'], unique=False)
    op.create_index('ix_stores_budgets_budget_code', 'stores_budgets', ['budget_code'], unique=True)
    op.create_table('stores_store_transfer_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transfer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uom_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['stores_categories.id'], name='stores_store_transfer_items_category_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['stores_items.id'], name='stores_store_transfer_items_item_id_fkey'),
    sa.ForeignKeyConstraint(['transfer_id'], ['stores_store_transfers.id'], name='stores_store_transfer_items_transfer_id_fkey'),
    sa.ForeignKeyConstraint(['uom_id'], ['stores_uoms.id'], name='stores_store_transfer_items_uom_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_store_transfer_items_pkey')
    )
    op.create_index('ix_stores_store_transfer_items_id', 'stores_store_transfer_items', ['id'], unique=False)
    op.create_table('stores_departments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stores_departments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('department_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('department_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('department_head', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stores_departments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stores_departments_id', 'stores_departments', ['id'], unique=False)
    op.create_index('ix_stores_departments_department_name', 'stores_departments', ['department_name'], unique=False)
    op.create_index('ix_stores_departments_department_code', 'stores_departments', ['department_code'], unique=True)
    op.create_table('stores_vendor_quotation_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quotation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uom_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quoted_unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gst', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('delivery_terms', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['stores_categories.id'], name='stores_vendor_quotation_items_category_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['stores_items.id'], name='stores_vendor_quotation_items_item_id_fkey'),
    sa.ForeignKeyConstraint(['quotation_id'], ['stores_vendor_quotations.id'], name='stores_vendor_quotation_items_quotation_id_fkey'),
    sa.ForeignKeyConstraint(['uom_id'], ['stores_uoms.id'], name='stores_vendor_quotation_items_uom_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_vendor_quotation_items_pkey')
    )
    op.create_index('ix_stores_vendor_quotation_items_id', 'stores_vendor_quotation_items', ['id'], unique=False)
    op.create_table('quotation_headers',
    sa.Column('quotation_id', sa.INTEGER(), server_default=sa.text("nextval('quotation_headers_quotation_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['stores_vendors.id'], name='quotation_headers_vendor_id_fkey'),
    sa.PrimaryKeyConstraint('quotation_id', name='quotation_headers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_quotation_headers_quotation_id', 'quotation_headers', ['quotation_id'], unique=False)
    op.create_table('stationary_grn',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stationary_grn_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('grn_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('gate_entry_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('po_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('vendor', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('vehicle_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('driver_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bill_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_provisional', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stationary_grn_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stationary_grn_id', 'stationary_grn', ['id'], unique=False)
    op.create_index('ix_stationary_grn_grn_no', 'stationary_grn', ['grn_no'], unique=True)
    op.create_table('stores_cost_centers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stores_cost_centers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stores_cost_centers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stores_cost_centers_id', 'stores_cost_centers', ['id'], unique=False)
    op.create_index('ix_stores_cost_centers_code', 'stores_cost_centers', ['code'], unique=True)
    op.create_table('loom_master',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('loom_master_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('loom_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('loom_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('installation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('capacity_per_day', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('running_speed_per_hr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('efficiency_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reed_width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_ends', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_service_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('next_service_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_warp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_weft', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='loom_master_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_loom_master_loom_name', 'loom_master', ['loom_name'], unique=True)
    op.create_index('ix_loom_master_id', 'loom_master', ['id'], unique=False)
    op.create_table('stores_stock_adjustment_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('adjustment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uom_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantity_adjusted', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('new_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['adjustment_id'], ['stores_stock_adjustments.id'], name='stores_stock_adjustment_items_adjustment_id_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['stores_categories.id'], name='stores_stock_adjustment_items_category_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['stores_items.id'], name='stores_stock_adjustment_items_item_id_fkey'),
    sa.ForeignKeyConstraint(['uom_id'], ['stores_uoms.id'], name='stores_stock_adjustment_items_uom_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_stock_adjustment_items_pkey')
    )
    op.create_index('ix_stores_stock_adjustment_items_id', 'stores_stock_adjustment_items', ['id'], unique=False)
    op.create_table('vendors',
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_info', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('vendor_id', name='vendors_pkey')
    )
    op.create_index('ix_vendors_vendor_name', 'vendors', ['vendor_name'], unique=False)
    op.create_index('ix_vendors_vendor_id', 'vendors', ['vendor_id'], unique=False)
    op.create_table('stationary_stock',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bin_id'], ['stationary_bins.id'], name='stationary_stock_bin_id_fkey'),
    sa.ForeignKeyConstraint(['material_id'], ['stationary_materials.id'], name='stationary_stock_material_id_fkey'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['stationary_warehouses.id'], name='stationary_stock_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stationary_stock_pkey')
    )
    op.create_index('ix_stationary_stock_id', 'stationary_stock', ['id'], unique=False)
    op.create_table('stationary_stock_issue_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['stationary_stock_issues.id'], name='stationary_stock_issue_items_issue_id_fkey'),
    sa.ForeignKeyConstraint(['material_id'], ['stationary_materials.id'], name='stationary_stock_issue_items_material_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stationary_stock_issue_items_pkey')
    )
    op.create_index('ix_stationary_stock_issue_items_id', 'stationary_stock_issue_items', ['id'], unique=False)
    op.create_table('stationary_racks',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stationary_racks_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('levels', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rows', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('columns', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['stationary_warehouses.id'], name='stationary_racks_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stationary_racks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stationary_racks_id', 'stationary_racks', ['id'], unique=False)
    op.create_table('stores_warehouses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stores_warehouses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('warehouse_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('warehouse_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stores_warehouses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stores_warehouses_warehouse_code', 'stores_warehouses', ['warehouse_code'], unique=True)
    op.create_index('ix_stores_warehouses_id', 'stores_warehouses', ['id'], unique=False)
    op.create_table('stationary_categories',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stationary_categories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['stationary_categories.id'], name='stationary_categories_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stationary_categories_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stationary_categories_name', 'stationary_categories', ['name'], unique=True)
    op.create_index('ix_stationary_categories_id', 'stationary_categories', ['id'], unique=False)
    op.create_table('stores_categories',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stores_categories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('category_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stores_categories_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stores_categories_id', 'stores_categories', ['id'], unique=False)
    op.create_index('ix_stores_categories_category_name', 'stores_categories', ['category_name'], unique=False)
    op.create_index('ix_stores_categories_category_code', 'stores_categories', ['category_code'], unique=True)
    op.create_table('stores_subcategories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subcategory_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('subcategory_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['stores_categories.id'], name='stores_subcategories_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_subcategories_pkey')
    )
    op.create_index('ix_stores_subcategories_subcategory_code', 'stores_subcategories', ['subcategory_code'], unique=True)
    op.create_index('ix_stores_subcategories_id', 'stores_subcategories', ['id'], unique=False)
    op.create_table('stationary_stock_issues',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('issue_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cost_center', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('requested_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('issued_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('purpose', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stationary_stock_issues_pkey')
    )
    op.create_index('ix_stationary_stock_issues_issue_no', 'stationary_stock_issues', ['issue_no'], unique=True)
    op.create_index('ix_stationary_stock_issues_id', 'stationary_stock_issues', ['id'], unique=False)
    op.create_table('operator_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('operator_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('skill_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assigned_loom', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assigned_shift', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('join_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('contact_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='operator_master_pkey')
    )
    op.create_index('ix_operator_master_operator_id', 'operator_master', ['operator_id'], unique=True)
    op.create_index('ix_operator_master_id', 'operator_master', ['id'], unique=False)
    op.create_table('production_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('allocation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meters_produced', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('downtime_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['loom_allocations.id'], name='production_logs_allocation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='production_logs_pkey')
    )
    op.create_index('ix_production_logs_id', 'production_logs', ['id'], unique=False)
    op.create_table('stores_vendor_quotations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quote_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('quote_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('validity_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('payment_terms', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('quotation_file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['stores_purchase_requisitions.id'], name='stores_vendor_quotations_pr_id_fkey'),
    sa.ForeignKeyConstraint(['vendor_id'], ['stores_vendors.id'], name='stores_vendor_quotations_vendor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_vendor_quotations_pkey')
    )
    op.create_index('ix_stores_vendor_quotations_quote_no', 'stores_vendor_quotations', ['quote_no'], unique=True)
    op.create_index('ix_stores_vendor_quotations_id', 'stores_vendor_quotations', ['id'], unique=False)
    op.create_table('stores_issue_to_departments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stores_issue_to_departments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('issue_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('requesting_department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('issued_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('received_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('issue_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['issued_by_id'], ['employees.id'], name='stores_issue_to_departments_issued_by_id_fkey'),
    sa.ForeignKeyConstraint(['received_by_id'], ['employees.id'], name='stores_issue_to_departments_received_by_id_fkey'),
    sa.ForeignKeyConstraint(['requesting_department_id'], ['stores_departments.id'], name='stores_issue_to_departments_requesting_department_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_issue_to_departments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stores_issue_to_departments_issue_no', 'stores_issue_to_departments', ['issue_no'], unique=True)
    op.create_index('ix_stores_issue_to_departments_id', 'stores_issue_to_departments', ['id'], unique=False)
    op.create_table('stores_returnable_dc_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dc_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uom_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('serial_batch_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('return_terms', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['stores_categories.id'], name='stores_returnable_dc_items_category_id_fkey'),
    sa.ForeignKeyConstraint(['dc_id'], ['stores_returnable_dcs.id'], name='stores_returnable_dc_items_dc_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['stores_items.id'], name='stores_returnable_dc_items_item_id_fkey'),
    sa.ForeignKeyConstraint(['uom_id'], ['stores_uoms.id'], name='stores_returnable_dc_items_uom_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_returnable_dc_items_pkey')
    )
    op.create_index('ix_stores_returnable_dc_items_id', 'stores_returnable_dc_items', ['id'], unique=False)
    op.create_table('stationary_grn_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grn_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('received_qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('accepted_qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rejected_qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('qc_remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['grn_id'], ['stationary_grn.id'], name='stationary_grn_items_grn_id_fkey'),
    sa.ForeignKeyConstraint(['material_id'], ['stationary_materials.id'], name='stationary_grn_items_material_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stationary_grn_items_pkey')
    )
    op.create_index('ix_stationary_grn_items_id', 'stationary_grn_items', ['id'], unique=False)
    op.create_table('stores_purchase_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('po_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pr_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quotation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('po_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expected_delivery_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivery_warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('delivery_department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('payment_terms', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('delivery_instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('discount_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tax_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('grand_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['delivery_department_id'], ['stores_departments.id'], name='stores_purchase_orders_delivery_department_id_fkey'),
    sa.ForeignKeyConstraint(['delivery_warehouse_id'], ['stores_warehouses.id'], name='stores_purchase_orders_delivery_warehouse_id_fkey'),
    sa.ForeignKeyConstraint(['pr_id'], ['stores_purchase_requisitions.id'], name='stores_purchase_orders_pr_id_fkey'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation_headers.quotation_id'], name='stores_purchase_orders_quotation_id_fkey'),
    sa.ForeignKeyConstraint(['vendor_id'], ['stores_vendors.id'], name='stores_purchase_orders_vendor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_purchase_orders_pkey')
    )
    op.create_index('ix_stores_purchase_orders_po_no', 'stores_purchase_orders', ['po_no'], unique=True)
    op.create_index('ix_stores_purchase_orders_id', 'stores_purchase_orders', ['id'], unique=False)
    op.create_table('stationary_materials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sub_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('material_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('abc_class', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('xyz_class', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('stock_criticality', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('base_uom_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alt_uom_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('conversion_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('min_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reorder_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reorder_qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('safety_stock', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lead_time_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hsn_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('gst_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('purchase_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('standard_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('default_warehouse_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('default_bin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('item_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('technical_spec', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['alt_uom_id'], ['stationary_uoms.id'], name='stationary_materials_alt_uom_id_fkey'),
    sa.ForeignKeyConstraint(['base_uom_id'], ['stationary_uoms.id'], name='stationary_materials_base_uom_id_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['stationary_categories.id'], name='stationary_materials_category_id_fkey'),
    sa.ForeignKeyConstraint(['default_bin_id'], ['stationary_bins.id'], name='stationary_materials_default_bin_id_fkey'),
    sa.ForeignKeyConstraint(['default_warehouse_id'], ['stationary_warehouses.id'], name='stationary_materials_default_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stationary_materials_pkey')
    )
    op.create_index('ix_stationary_materials_item_code', 'stationary_materials', ['item_code'], unique=True)
    op.create_index('ix_stationary_materials_id', 'stationary_materials', ['id'], unique=False)
    op.create_table('stores_stock_adjustments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('adjustment_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('adjustment_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('adjusted_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('authorized_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['adjusted_by_id'], ['employees.id'], name='stores_stock_adjustments_adjusted_by_id_fkey'),
    sa.ForeignKeyConstraint(['authorized_by_id'], ['employees.id'], name='stores_stock_adjustments_authorized_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_stock_adjustments_pkey')
    )
    op.create_index('ix_stores_stock_adjustments_id', 'stores_stock_adjustments', ['id'], unique=False)
    op.create_index('ix_stores_stock_adjustments_adjustment_no', 'stores_stock_adjustments', ['adjustment_no'], unique=True)
    op.create_table('stores_issue_to_department_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uom_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_requested', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantity_issued', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['stores_categories.id'], name='stores_issue_to_department_items_category_id_fkey'),
    sa.ForeignKeyConstraint(['issue_id'], ['stores_issue_to_departments.id'], name='stores_issue_to_department_items_issue_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['stores_items.id'], name='stores_issue_to_department_items_item_id_fkey'),
    sa.ForeignKeyConstraint(['uom_id'], ['stores_uoms.id'], name='stores_issue_to_department_items_uom_id_fkey'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['stores_warehouses.id'], name='stores_issue_to_department_items_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_issue_to_department_items_pkey')
    )
    op.create_index('ix_stores_issue_to_department_items_id', 'stores_issue_to_department_items', ['id'], unique=False)
    op.create_table('stores_material_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uom_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['stores_categories.id'], name='stores_material_requests_category_id_fkey'),
    sa.ForeignKeyConstraint(['department_id'], ['stores_departments.id'], name='stores_material_requests_department_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['stores_items.id'], name='stores_material_requests_item_id_fkey'),
    sa.ForeignKeyConstraint(['uom_id'], ['stores_uoms.id'], name='stores_material_requests_uom_id_fkey'),
    sa.ForeignKeyConstraint(['vendor_id'], ['stores_vendors.id'], name='stores_material_requests_vendor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_material_requests_pkey')
    )
    op.create_index('ix_stores_material_requests_request_no', 'stores_material_requests', ['request_no'], unique=True)
    op.create_index('ix_stores_material_requests_id', 'stores_material_requests', ['id'], unique=False)
    # ### end Alembic commands ###
