"""Update Yarn Inward Schema

Revision ID: 992a367333f2
Revises: de2d1bc28137
Create Date: 2026-05-26 17:04:15.487901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992a367333f2'
down_revision: Union[str, None] = 'de2d1bc28137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yarn_inward_items', sa.Column('yarn_count', sa.String(length=100), nullable=True))
    op.add_column('yarn_inward_items', sa.Column('mill_name', sa.String(length=255), nullable=True))
    op.add_column('yarn_inward_items', sa.Column('colour', sa.String(length=100), nullable=True))
    op.add_column('yarn_inward_items', sa.Column('color_code', sa.String(length=100), nullable=True))
    op.add_column('yarn_inward_items', sa.Column('our_id', sa.String(length=100), nullable=True))
    op.add_column('yarn_inward_items', sa.Column('kgs', sa.Float(), nullable=True))
    op.alter_column('yarn_inward_items', 'lot_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('yarn_inward_items', 'rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('yarn_inward_items', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('yarn_inward_items', 'color')
    op.drop_column('yarn_inward_items', 'yarn_type')
    op.drop_column('yarn_inward_items', 'count')
    op.drop_column('yarn_inward_items', 'cones')
    op.drop_column('yarn_inward_items', 'total_kgs')
    op.drop_column('yarn_inward_items', 'stock')
    op.add_column('yarn_inwards', sa.Column('entry_date', sa.Date(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('inward_date', sa.Date(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('received_from', sa.String(length=255), nullable=True))
    op.add_column('yarn_inwards', sa.Column('po_no_dt', sa.String(length=100), nullable=True))
    op.add_column('yarn_inwards', sa.Column('agent_name', sa.String(length=255), nullable=True))
    op.add_column('yarn_inwards', sa.Column('stock_godown', sa.String(length=255), nullable=True))
    op.add_column('yarn_inwards', sa.Column('godown_id', sa.Integer(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('cone_type', sa.String(length=50), nullable=True))
    op.add_column('yarn_inwards', sa.Column('order_kgs', sa.Float(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('received_kgs', sa.Float(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('balance_kgs', sa.Float(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('pc_id', sa.String(length=100), nullable=True))
    op.add_column('yarn_inwards', sa.Column('tolerance_pct', sa.Float(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('bill_no', sa.String(length=100), nullable=True))
    op.add_column('yarn_inwards', sa.Column('bill_amount', sa.Float(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('gross_kgs', sa.Float(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('net_kgs', sa.Float(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('chipnam', sa.String(length=100), nullable=True))
    op.add_column('yarn_inwards', sa.Column('due_days', sa.Integer(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('transport', sa.String(length=255), nullable=True))
    op.add_column('yarn_inwards', sa.Column('veh_no', sa.String(length=100), nullable=True))
    op.add_column('yarn_inwards', sa.Column('total_bags', sa.Integer(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('eway_bill', sa.String(length=100), nullable=True))
    op.add_column('yarn_inwards', sa.Column('org_grn_no', sa.String(length=100), nullable=True))
    op.add_column('yarn_inwards', sa.Column('gate_no', sa.String(length=100), nullable=True))
    op.add_column('yarn_inwards', sa.Column('wbridge_no', sa.String(length=100), nullable=True))
    op.add_column('yarn_inwards', sa.Column('w_weight', sa.Float(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('other_remarks', sa.Text(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('packing', sa.String(length=100), nullable=True))
    op.add_column('yarn_inwards', sa.Column('freight', sa.Float(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('tax_type', sa.String(length=100), nullable=True))
    op.add_column('yarn_inwards', sa.Column('cgst_pct', sa.Float(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('sgst_pct', sa.Float(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('igst_pct', sa.Float(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('tax_value', sa.Float(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('tcs_value', sa.Float(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('tds_pct', sa.Float(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('total_tax', sa.Float(), nullable=True))
    op.add_column('yarn_inwards', sa.Column('round_off', sa.Float(), nullable=True))
    op.alter_column('yarn_inwards', 'gross_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('yarn_inwards', 'net_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint('yarn_inwards_party_id_fkey', 'yarn_inwards', type_='foreignkey')
    op.drop_column('yarn_inwards', 'inv_date')
    op.drop_column('yarn_inwards', 'order_no')
    op.drop_column('yarn_inwards', 'igst')
    op.drop_column('yarn_inwards', 'inv_no')
    op.drop_column('yarn_inwards', 'dc_no')
    op.drop_column('yarn_inwards', 'party_id')
    op.drop_column('yarn_inwards', 'party_name')
    op.drop_column('yarn_inwards', 'dc_date')
    op.drop_column('yarn_inwards', 'design_no')
    op.drop_column('yarn_inwards', 'sgst')
    op.drop_column('yarn_inwards', 'total_kgs')
    op.drop_column('yarn_inwards', 'receive_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yarn_inwards', sa.Column('receive_mode', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('total_kgs', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('sgst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('design_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('dc_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('party_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('dc_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('inv_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('igst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('order_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('yarn_inwards', sa.Column('inv_date', sa.DATE(), autoincrement=False, nullable=True))
    op.create_foreign_key('yarn_inwards_party_id_fkey', 'yarn_inwards', 'party_master', ['party_id'], ['id'])
    op.alter_column('yarn_inwards', 'net_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('yarn_inwards', 'gross_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=True)
    op.drop_column('yarn_inwards', 'round_off')
    op.drop_column('yarn_inwards', 'total_tax')
    op.drop_column('yarn_inwards', 'tds_pct')
    op.drop_column('yarn_inwards', 'tcs_value')
    op.drop_column('yarn_inwards', 'tax_value')
    op.drop_column('yarn_inwards', 'igst_pct')
    op.drop_column('yarn_inwards', 'sgst_pct')
    op.drop_column('yarn_inwards', 'cgst_pct')
    op.drop_column('yarn_inwards', 'tax_type')
    op.drop_column('yarn_inwards', 'freight')
    op.drop_column('yarn_inwards', 'packing')
    op.drop_column('yarn_inwards', 'other_remarks')
    op.drop_column('yarn_inwards', 'w_weight')
    op.drop_column('yarn_inwards', 'wbridge_no')
    op.drop_column('yarn_inwards', 'gate_no')
    op.drop_column('yarn_inwards', 'org_grn_no')
    op.drop_column('yarn_inwards', 'eway_bill')
    op.drop_column('yarn_inwards', 'total_bags')
    op.drop_column('yarn_inwards', 'veh_no')
    op.drop_column('yarn_inwards', 'transport')
    op.drop_column('yarn_inwards', 'due_days')
    op.drop_column('yarn_inwards', 'chipnam')
    op.drop_column('yarn_inwards', 'net_kgs')
    op.drop_column('yarn_inwards', 'gross_kgs')
    op.drop_column('yarn_inwards', 'bill_amount')
    op.drop_column('yarn_inwards', 'bill_no')
    op.drop_column('yarn_inwards', 'tolerance_pct')
    op.drop_column('yarn_inwards', 'pc_id')
    op.drop_column('yarn_inwards', 'balance_kgs')
    op.drop_column('yarn_inwards', 'received_kgs')
    op.drop_column('yarn_inwards', 'order_kgs')
    op.drop_column('yarn_inwards', 'cone_type')
    op.drop_column('yarn_inwards', 'godown_id')
    op.drop_column('yarn_inwards', 'stock_godown')
    op.drop_column('yarn_inwards', 'agent_name')
    op.drop_column('yarn_inwards', 'po_no_dt')
    op.drop_column('yarn_inwards', 'received_from')
    op.drop_column('yarn_inwards', 'inward_date')
    op.drop_column('yarn_inwards', 'entry_date')
    op.add_column('yarn_inward_items', sa.Column('stock', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('yarn_inward_items', sa.Column('total_kgs', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_inward_items', sa.Column('cones', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('yarn_inward_items', sa.Column('count', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('yarn_inward_items', sa.Column('yarn_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('yarn_inward_items', sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('yarn_inward_items', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('yarn_inward_items', 'rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('yarn_inward_items', 'lot_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('yarn_inward_items', 'kgs')
    op.drop_column('yarn_inward_items', 'our_id')
    op.drop_column('yarn_inward_items', 'color_code')
    op.drop_column('yarn_inward_items', 'colour')
    op.drop_column('yarn_inward_items', 'mill_name')
    op.drop_column('yarn_inward_items', 'yarn_count')
    # ### end Alembic commands ###
