"""Merge models

Revision ID: c06f49524b09
Revises: 
Create Date: 2026-05-26 15:07:41.151769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06f49524b09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_general_master_category', table_name='general_master')
    op.drop_index('ix_general_master_id', table_name='general_master')
    op.drop_table('general_master')
    op.create_foreign_key(None, 'buyer_orders', 'party_master', ['party_id'], ['id'])
    op.add_column('employees', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('user_type', sa.String(length=30), nullable=True))
    op.add_column('employees', sa.Column('web_access', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('company_depl', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('company_mtm', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('module_permissions', sa.JSON(), nullable=True))
    op.add_column('employees', sa.Column('menu_permissions', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'employees', ['email'])
    op.create_foreign_key(None, 'grey_yarn_deliveries', 'party_master', ['party_id'], ['id'])
    op.add_column('party_master', sa.Column('company_name', sa.String(length=255), server_default='Unknown', nullable=False))
    op.add_column('party_master', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('party_master', sa.Column('pin_code', sa.String(length=20), nullable=True))
    op.add_column('party_master', sa.Column('mobile', sa.String(length=20), nullable=True))
    op.add_column('party_master', sa.Column('gst_no', sa.String(length=50), nullable=True))
    op.add_column('party_master', sa.Column('bank_name', sa.String(length=150), nullable=True))
    op.add_column('party_master', sa.Column('bank_account', sa.String(length=50), nullable=True))
    op.add_column('party_master', sa.Column('ifsc_code', sa.String(length=15), nullable=True))
    op.add_column('party_master', sa.Column('credit_days', sa.Integer(), nullable=True))
    op.alter_column('party_master', 'state_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.drop_column('party_master', 'gstin')
    op.drop_column('party_master', 'bill_credit_days')
    op.drop_column('party_master', 'business_name')
    op.drop_column('party_master', 'pincode')
    op.create_foreign_key(None, 'sales_invoices', 'party_master', ['party_id'], ['id'])
    op.create_foreign_key(None, 'yarn_inwards', 'party_master', ['party_id'], ['id'])
    op.create_foreign_key(None, 'yarn_purchase_orders', 'party_master', ['party_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yarn_purchase_orders', type_='foreignkey')
    op.drop_constraint(None, 'yarn_inwards', type_='foreignkey')
    op.drop_constraint(None, 'sales_invoices', type_='foreignkey')
    op.add_column('party_master', sa.Column('pincode', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('party_master', sa.Column('business_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('party_master', sa.Column('bill_credit_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('party_master', sa.Column('gstin', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('party_master', 'state_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('party_master', 'credit_days')
    op.drop_column('party_master', 'ifsc_code')
    op.drop_column('party_master', 'bank_account')
    op.drop_column('party_master', 'bank_name')
    op.drop_column('party_master', 'gst_no')
    op.drop_column('party_master', 'mobile')
    op.drop_column('party_master', 'pin_code')
    op.drop_column('party_master', 'state')
    op.drop_column('party_master', 'company_name')
    op.drop_constraint(None, 'grey_yarn_deliveries', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'menu_permissions')
    op.drop_column('employees', 'module_permissions')
    op.drop_column('employees', 'company_mtm')
    op.drop_column('employees', 'company_depl')
    op.drop_column('employees', 'web_access')
    op.drop_column('employees', 'user_type')
    op.drop_column('employees', 'email')
    op.drop_constraint(None, 'buyer_orders', type_='foreignkey')
    op.create_table('general_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='general_master_pkey')
    )
    op.create_index('ix_general_master_id', 'general_master', ['id'], unique=False)
    op.create_index('ix_general_master_category', 'general_master', ['category'], unique=False)
    # ### end Alembic commands ###
