"""Update Grey Yarn Delivery Schema

Revision ID: c777b2fd0966
Revises: 992a367333f2
Create Date: 2026-05-26 17:17:52.419080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c777b2fd0966'
down_revision: Union[str, None] = '992a367333f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grey_yarn_deliveries', sa.Column('ref_date', sa.Date(), nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('stock_godown', sa.String(length=255), nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('delivery_address', sa.Text(), nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('vehicle_no', sa.String(length=100), nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('delivery_name', sa.String(length=255), nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('delivery_time', sa.String(length=20), nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('design_count', sa.String(length=100), nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('order_kgs', sa.Float(), nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('total_dely_kgs', sa.Float(), nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('total_rtn_kgs', sa.Float(), nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('balance_kgs', sa.Float(), nullable=True))
    op.alter_column('grey_yarn_deliveries', 'delivery_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'delivery_mode',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'design_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'order_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'transport',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'certificate_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint('grey_yarn_deliveries_party_id_fkey', 'grey_yarn_deliveries', type_='foreignkey')
    op.drop_column('grey_yarn_deliveries', 'remarks')
    op.drop_column('grey_yarn_deliveries', 'igst')
    op.drop_column('grey_yarn_deliveries', 'net_amount')
    op.drop_column('grey_yarn_deliveries', 'gross_amount')
    op.drop_column('grey_yarn_deliveries', 'party_id')
    op.drop_column('grey_yarn_deliveries', 'total_kgs')
    op.drop_column('grey_yarn_deliveries', 'sgst')
    op.add_column('grey_yarn_delivery_items', sa.Column('cone_type', sa.String(length=50), nullable=True))
    op.add_column('grey_yarn_delivery_items', sa.Column('our_lot_no', sa.String(length=100), nullable=True))
    op.alter_column('grey_yarn_delivery_items', 'count',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'color',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'stock',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using="stock::double precision")
    op.alter_column('grey_yarn_delivery_items', 'total_kgs',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('grey_yarn_delivery_items', 'lot_no')
    op.drop_column('grey_yarn_delivery_items', 'yarn_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grey_yarn_delivery_items', sa.Column('yarn_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('grey_yarn_delivery_items', sa.Column('lot_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('grey_yarn_delivery_items', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'total_kgs',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'stock',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'color',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('grey_yarn_delivery_items', 'count',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('grey_yarn_delivery_items', 'our_lot_no')
    op.drop_column('grey_yarn_delivery_items', 'cone_type')
    op.add_column('grey_yarn_deliveries', sa.Column('sgst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('total_kgs', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('gross_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('net_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('igst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('grey_yarn_deliveries', sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('grey_yarn_deliveries_party_id_fkey', 'grey_yarn_deliveries', 'party_master', ['party_id'], ['id'])
    op.alter_column('grey_yarn_deliveries', 'certificate_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'transport',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'order_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'design_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'delivery_mode',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('grey_yarn_deliveries', 'delivery_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('grey_yarn_deliveries', 'balance_kgs')
    op.drop_column('grey_yarn_deliveries', 'total_rtn_kgs')
    op.drop_column('grey_yarn_deliveries', 'total_dely_kgs')
    op.drop_column('grey_yarn_deliveries', 'order_kgs')
    op.drop_column('grey_yarn_deliveries', 'design_count')
    op.drop_column('grey_yarn_deliveries', 'delivery_time')
    op.drop_column('grey_yarn_deliveries', 'delivery_name')
    op.drop_column('grey_yarn_deliveries', 'vehicle_no')
    op.drop_column('grey_yarn_deliveries', 'delivery_address')
    op.drop_column('grey_yarn_deliveries', 'stock_godown')
    op.drop_column('grey_yarn_deliveries', 'ref_date')
    # ### end Alembic commands ###
