"""Update Yarn Purchase Order Schema

Revision ID: de2d1bc28137
Revises: 721bd7eb0e15
Create Date: 2026-05-26 16:57:36.940389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de2d1bc28137'
down_revision: Union[str, None] = '721bd7eb0e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_yarn_purchase_items_id', table_name='yarn_purchase_items')
    op.drop_table('yarn_purchase_items')
    op.add_column('yarn_purchase_orders', sa.Column('org_name', sa.String(length=255), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('internal_po_no', sa.String(length=100), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('used_for', sa.String(length=100), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('against_ref', sa.String(length=100), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('agent_name', sa.String(length=255), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('supplier_name', sa.String(length=255), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('delivery_at', sa.String(length=255), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('freight_type', sa.String(length=100), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('freight_chg', sa.Float(), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('insurance_chg', sa.Float(), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('total_order_kgs', sa.Float(), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('transport', sa.String(length=255), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('tax_type', sa.String(length=100), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('taxable_amount', sa.Float(), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('dispatch_date', sa.Date(), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('packing_type', sa.String(length=100), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('sgst_pct', sa.Float(), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('cgst_pct', sa.Float(), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('igst_pct', sa.Float(), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('labeling', sa.String(length=255), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('colour', sa.String(length=100), nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('due_days', sa.Integer(), nullable=True))
    op.alter_column('yarn_purchase_orders', 'net_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint('yarn_purchase_orders_party_id_fkey', 'yarn_purchase_orders', type_='foreignkey')
    op.drop_column('yarn_purchase_orders', 'payment_terms')
    op.drop_column('yarn_purchase_orders', 'sgst')
    op.drop_column('yarn_purchase_orders', 'design_no')
    op.drop_column('yarn_purchase_orders', 'total_amount')
    op.drop_column('yarn_purchase_orders', 'party_id')
    op.drop_column('yarn_purchase_orders', 'party_name')
    op.drop_column('yarn_purchase_orders', 'igst')
    op.drop_column('yarn_purchase_orders', 'order_type')
    op.drop_column('yarn_purchase_orders', 'cgst')
    op.drop_column('yarn_purchase_orders', 'delivery_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yarn_purchase_orders', sa.Column('delivery_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('cgst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('order_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('igst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('party_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('total_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('design_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('sgst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('yarn_purchase_orders', sa.Column('payment_terms', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_foreign_key('yarn_purchase_orders_party_id_fkey', 'yarn_purchase_orders', 'party_master', ['party_id'], ['id'])
    op.alter_column('yarn_purchase_orders', 'net_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=True)
    op.drop_column('yarn_purchase_orders', 'due_days')
    op.drop_column('yarn_purchase_orders', 'colour')
    op.drop_column('yarn_purchase_orders', 'labeling')
    op.drop_column('yarn_purchase_orders', 'igst_pct')
    op.drop_column('yarn_purchase_orders', 'cgst_pct')
    op.drop_column('yarn_purchase_orders', 'sgst_pct')
    op.drop_column('yarn_purchase_orders', 'packing_type')
    op.drop_column('yarn_purchase_orders', 'dispatch_date')
    op.drop_column('yarn_purchase_orders', 'taxable_amount')
    op.drop_column('yarn_purchase_orders', 'tax_type')
    op.drop_column('yarn_purchase_orders', 'transport')
    op.drop_column('yarn_purchase_orders', 'total_order_kgs')
    op.drop_column('yarn_purchase_orders', 'insurance_chg')
    op.drop_column('yarn_purchase_orders', 'freight_chg')
    op.drop_column('yarn_purchase_orders', 'freight_type')
    op.drop_column('yarn_purchase_orders', 'delivery_at')
    op.drop_column('yarn_purchase_orders', 'supplier_name')
    op.drop_column('yarn_purchase_orders', 'agent_name')
    op.drop_column('yarn_purchase_orders', 'against_ref')
    op.drop_column('yarn_purchase_orders', 'used_for')
    op.drop_column('yarn_purchase_orders', 'internal_po_no')
    op.drop_column('yarn_purchase_orders', 'org_name')
    op.create_table('yarn_purchase_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('po_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('yarn_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('count', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('lot_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('bags', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cones', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_kgs', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['yarn_purchase_orders.id'], name='yarn_purchase_items_po_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='yarn_purchase_items_pkey')
    )
    op.create_index('ix_yarn_purchase_items_id', 'yarn_purchase_items', ['id'], unique=False)
    # ### end Alembic commands ###
