"""Add dyed yarn delivery fields

Revision ID: e0c14510b1a3
Revises: 10c1a8bac83a
Create Date: 2026-05-26 19:45:10.814067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c14510b1a3'
down_revision: Union[str, None] = '10c1a8bac83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dyed_yarn_deliveries', sa.Column('add_date', sa.Date(), nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('delivery_time', sa.String(length=50), nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('insurance', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('other_charges', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('tax_value', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('total_gst', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('dyed_yarn_deliveries', sa.Column('round_off', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dyed_yarn_deliveries', 'round_off')
    op.drop_column('dyed_yarn_deliveries', 'total_gst')
    op.drop_column('dyed_yarn_deliveries', 'tax_value')
    op.drop_column('dyed_yarn_deliveries', 'other_charges')
    op.drop_column('dyed_yarn_deliveries', 'insurance')
    op.drop_column('dyed_yarn_deliveries', 'cost')
    op.drop_column('dyed_yarn_deliveries', 'delivery_time')
    op.drop_column('dyed_yarn_deliveries', 'add_date')
    # ### end Alembic commands ###
